# coding: utf-8

"""
    aind-smartsheet-service

     ## aind-smartsheet-service  Service to pull data from SmartSheet.  

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from aind_smartsheet_service_client.models.imaging_queue import ImagingQueue
from aind_smartsheet_service_client.models.mouse_tracker import MouseTracker
from aind_smartsheet_service_client.models.qc_sheet import QcSheet
from aind_smartsheet_service_client.models.sample_tracking import SampleTracking
from typing import Optional, Set
from typing_extensions import Self

class ExaSPIMInfo(BaseModel):
    """
    All exaSPIM Information for Specimen ID
    """ # noqa: E501
    mouse_tracker_info: Optional[List[MouseTracker]] = None
    sample_tracking_info: Optional[List[SampleTracking]] = None
    imaging_queue_info: Optional[List[ImagingQueue]] = None
    qc_sheet_info: Optional[List[QcSheet]] = None
    __properties: ClassVar[List[str]] = ["mouse_tracker_info", "sample_tracking_info", "imaging_queue_info", "qc_sheet_info"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExaSPIMInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in mouse_tracker_info (list)
        _items = []
        if self.mouse_tracker_info:
            for _item_mouse_tracker_info in self.mouse_tracker_info:
                if _item_mouse_tracker_info:
                    _items.append(_item_mouse_tracker_info.to_dict())
            _dict['mouse_tracker_info'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in sample_tracking_info (list)
        _items = []
        if self.sample_tracking_info:
            for _item_sample_tracking_info in self.sample_tracking_info:
                if _item_sample_tracking_info:
                    _items.append(_item_sample_tracking_info.to_dict())
            _dict['sample_tracking_info'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in imaging_queue_info (list)
        _items = []
        if self.imaging_queue_info:
            for _item_imaging_queue_info in self.imaging_queue_info:
                if _item_imaging_queue_info:
                    _items.append(_item_imaging_queue_info.to_dict())
            _dict['imaging_queue_info'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in qc_sheet_info (list)
        _items = []
        if self.qc_sheet_info:
            for _item_qc_sheet_info in self.qc_sheet_info:
                if _item_qc_sheet_info:
                    _items.append(_item_qc_sheet_info.to_dict())
            _dict['qc_sheet_info'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExaSPIMInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "mouse_tracker_info": [MouseTracker.from_dict(_item) for _item in obj["mouse_tracker_info"]] if obj.get("mouse_tracker_info") is not None else None,
            "sample_tracking_info": [SampleTracking.from_dict(_item) for _item in obj["sample_tracking_info"]] if obj.get("sample_tracking_info") is not None else None,
            "imaging_queue_info": [ImagingQueue.from_dict(_item) for _item in obj["imaging_queue_info"]] if obj.get("imaging_queue_info") is not None else None,
            "qc_sheet_info": [QcSheet.from_dict(_item) for _item in obj["qc_sheet_info"]] if obj.get("qc_sheet_info") is not None else None
        })
        return _obj


