# coding: utf-8

"""
    aind-smartsheet-service

     ## aind-smartsheet-service  Service to pull data from SmartSheet.  

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ImagingQueue(BaseModel):
    """
    Imaging Queue Sheet Information.
    """ # noqa: E501
    count: Optional[StrictStr] = None
    sample: Optional[StrictStr] = None
    one_x_imaging_date: Optional[StrictStr] = None
    imaging_start_date: Optional[StrictStr] = None
    imaging_start_time: Optional[StrictStr] = None
    drop_off_date: Optional[StrictStr] = None
    imaging_end_date: Optional[StrictStr] = None
    imaging_end_time: Optional[StrictStr] = None
    imaging_buffer: Optional[StrictStr] = None
    microscope: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    genotype: Optional[StrictStr] = None
    label: Optional[StrictStr] = None
    fluorophore: Optional[StrictStr] = None
    signal_channel_s: Optional[StrictStr] = None
    auto_fluorescence_channel_s: Optional[StrictStr] = None
    focus_n_mm: Optional[StrictStr] = None
    etl_offset: Optional[StrictStr] = None
    notes: Optional[StrictStr] = None
    notes_1: Optional[StrictStr] = None
    verified_mouse_tracker_for_metadata_intake: Optional[StrictStr] = None
    notes_on_missing_metadata: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["count", "sample", "one_x_imaging_date", "imaging_start_date", "imaging_start_time", "drop_off_date", "imaging_end_date", "imaging_end_time", "imaging_buffer", "microscope", "status", "genotype", "label", "fluorophore", "signal_channel_s", "auto_fluorescence_channel_s", "focus_n_mm", "etl_offset", "notes", "notes_1", "verified_mouse_tracker_for_metadata_intake", "notes_on_missing_metadata"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ImagingQueue from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if count (nullable) is None
        # and model_fields_set contains the field
        if self.count is None and "count" in self.model_fields_set:
            _dict['count'] = None

        # set to None if sample (nullable) is None
        # and model_fields_set contains the field
        if self.sample is None and "sample" in self.model_fields_set:
            _dict['sample'] = None

        # set to None if one_x_imaging_date (nullable) is None
        # and model_fields_set contains the field
        if self.one_x_imaging_date is None and "one_x_imaging_date" in self.model_fields_set:
            _dict['one_x_imaging_date'] = None

        # set to None if imaging_start_date (nullable) is None
        # and model_fields_set contains the field
        if self.imaging_start_date is None and "imaging_start_date" in self.model_fields_set:
            _dict['imaging_start_date'] = None

        # set to None if imaging_start_time (nullable) is None
        # and model_fields_set contains the field
        if self.imaging_start_time is None and "imaging_start_time" in self.model_fields_set:
            _dict['imaging_start_time'] = None

        # set to None if drop_off_date (nullable) is None
        # and model_fields_set contains the field
        if self.drop_off_date is None and "drop_off_date" in self.model_fields_set:
            _dict['drop_off_date'] = None

        # set to None if imaging_end_date (nullable) is None
        # and model_fields_set contains the field
        if self.imaging_end_date is None and "imaging_end_date" in self.model_fields_set:
            _dict['imaging_end_date'] = None

        # set to None if imaging_end_time (nullable) is None
        # and model_fields_set contains the field
        if self.imaging_end_time is None and "imaging_end_time" in self.model_fields_set:
            _dict['imaging_end_time'] = None

        # set to None if imaging_buffer (nullable) is None
        # and model_fields_set contains the field
        if self.imaging_buffer is None and "imaging_buffer" in self.model_fields_set:
            _dict['imaging_buffer'] = None

        # set to None if microscope (nullable) is None
        # and model_fields_set contains the field
        if self.microscope is None and "microscope" in self.model_fields_set:
            _dict['microscope'] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        # set to None if genotype (nullable) is None
        # and model_fields_set contains the field
        if self.genotype is None and "genotype" in self.model_fields_set:
            _dict['genotype'] = None

        # set to None if label (nullable) is None
        # and model_fields_set contains the field
        if self.label is None and "label" in self.model_fields_set:
            _dict['label'] = None

        # set to None if fluorophore (nullable) is None
        # and model_fields_set contains the field
        if self.fluorophore is None and "fluorophore" in self.model_fields_set:
            _dict['fluorophore'] = None

        # set to None if signal_channel_s (nullable) is None
        # and model_fields_set contains the field
        if self.signal_channel_s is None and "signal_channel_s" in self.model_fields_set:
            _dict['signal_channel_s'] = None

        # set to None if auto_fluorescence_channel_s (nullable) is None
        # and model_fields_set contains the field
        if self.auto_fluorescence_channel_s is None and "auto_fluorescence_channel_s" in self.model_fields_set:
            _dict['auto_fluorescence_channel_s'] = None

        # set to None if focus_n_mm (nullable) is None
        # and model_fields_set contains the field
        if self.focus_n_mm is None and "focus_n_mm" in self.model_fields_set:
            _dict['focus_n_mm'] = None

        # set to None if etl_offset (nullable) is None
        # and model_fields_set contains the field
        if self.etl_offset is None and "etl_offset" in self.model_fields_set:
            _dict['etl_offset'] = None

        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict['notes'] = None

        # set to None if notes_1 (nullable) is None
        # and model_fields_set contains the field
        if self.notes_1 is None and "notes_1" in self.model_fields_set:
            _dict['notes_1'] = None

        # set to None if verified_mouse_tracker_for_metadata_intake (nullable) is None
        # and model_fields_set contains the field
        if self.verified_mouse_tracker_for_metadata_intake is None and "verified_mouse_tracker_for_metadata_intake" in self.model_fields_set:
            _dict['verified_mouse_tracker_for_metadata_intake'] = None

        # set to None if notes_on_missing_metadata (nullable) is None
        # and model_fields_set contains the field
        if self.notes_on_missing_metadata is None and "notes_on_missing_metadata" in self.model_fields_set:
            _dict['notes_on_missing_metadata'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ImagingQueue from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "count": obj.get("count"),
            "sample": obj.get("sample"),
            "one_x_imaging_date": obj.get("one_x_imaging_date"),
            "imaging_start_date": obj.get("imaging_start_date"),
            "imaging_start_time": obj.get("imaging_start_time"),
            "drop_off_date": obj.get("drop_off_date"),
            "imaging_end_date": obj.get("imaging_end_date"),
            "imaging_end_time": obj.get("imaging_end_time"),
            "imaging_buffer": obj.get("imaging_buffer"),
            "microscope": obj.get("microscope"),
            "status": obj.get("status"),
            "genotype": obj.get("genotype"),
            "label": obj.get("label"),
            "fluorophore": obj.get("fluorophore"),
            "signal_channel_s": obj.get("signal_channel_s"),
            "auto_fluorescence_channel_s": obj.get("auto_fluorescence_channel_s"),
            "focus_n_mm": obj.get("focus_n_mm"),
            "etl_offset": obj.get("etl_offset"),
            "notes": obj.get("notes"),
            "notes_1": obj.get("notes_1"),
            "verified_mouse_tracker_for_metadata_intake": obj.get("verified_mouse_tracker_for_metadata_intake"),
            "notes_on_missing_metadata": obj.get("notes_on_missing_metadata")
        })
        return _obj


