# coding: utf-8

"""
    aind-smartsheet-service

     ## aind-smartsheet-service  Service to pull data from SmartSheet.  

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class MouseTracker(BaseModel):
    """
    Mouse Tracker Sheet Information.
    """ # noqa: E501
    num: StrictInt
    ex_m_processing_status: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    mouse_id: Optional[StrictStr] = None
    sample_name: Optional[StrictStr] = None
    workflow: Optional[StrictStr] = None
    project_description: Optional[StrictStr] = None
    expression_time_days: Optional[StrictStr] = None
    pedigree: Optional[StrictStr] = None
    sex: Optional[StrictStr] = None
    dob: Optional[StrictStr] = None
    stx_injection_requested: Optional[StrictStr] = None
    ro_injection_requested: Optional[StrictStr] = None
    perfusion_requested: Optional[StrictStr] = None
    inj_details_tam_dose: Optional[StrictStr] = None
    tam_dosing_last_day: Optional[StrictStr] = None
    label: Optional[StrictStr] = None
    virus_mix_ro: Optional[StrictStr] = None
    virus_mix_total_volume_injected_ro_ul: Optional[StrictStr] = None
    virus_mix_vehicle_ro: Optional[StrictStr] = None
    virus1_injection_date: Optional[StrictStr] = None
    virus1_age_of_injection: Optional[StrictStr] = None
    virus1_injection_type: Optional[StrictStr] = None
    virus1: Optional[StrictStr] = None
    ai_p_num: Optional[StrictStr] = None
    virus1_id: Optional[StrictStr] = None
    virus1_stock_titer_gc_ml: Optional[StrictStr] = None
    working_titer_gc_ml: Optional[StrictStr] = None
    virus1_dose_gc: Optional[StrictStr] = None
    virus1_ap_mm: Optional[StrictStr] = None
    virus1_ml_mm: Optional[StrictStr] = None
    virus1_dv_mm: Optional[StrictStr] = None
    virus1_dv_b_mm: Optional[StrictStr] = None
    virus1_stereotaxic_volume_injected_nl: Optional[StrictStr] = None
    virus2_injection_date: Optional[StrictStr] = None
    virus2_age_of_injection: Optional[StrictStr] = None
    virus2_injection_type: Optional[StrictStr] = None
    virus2: Optional[StrictStr] = None
    virus2_ai_p_num: Optional[StrictStr] = None
    virus2_id: Optional[StrictStr] = None
    virus2_stock_titer_gc_ml: Optional[StrictStr] = None
    virus2_working_titer_gc_ml: Optional[StrictStr] = None
    virus2_dose_gc: Optional[StrictStr] = None
    virus2_effective_titer_gc_ml: Optional[StrictStr] = None
    virus2_ap_mm: Optional[StrictStr] = None
    virus2_ml_mm: Optional[StrictStr] = None
    virus2_dv_mm: Optional[StrictStr] = None
    virus2_dv_b_mm: Optional[StrictStr] = None
    virus2_stereotaxic_volume_injected_nl: Optional[StrictStr] = None
    virus3_injection_date: Optional[StrictStr] = None
    virus3_age_of_injection: Optional[StrictStr] = None
    virus3_injection_type: Optional[StrictStr] = None
    virus3: Optional[StrictStr] = None
    virus3_ai_p_num: Optional[StrictStr] = None
    virus3_id: Optional[StrictStr] = None
    virus3_stock_titer_gc_ml: Optional[StrictStr] = None
    virus3_dose_gc: Optional[StrictStr] = None
    virus3_effective_titer_gc_ml: Optional[StrictStr] = None
    virus3_ap_mm: Optional[StrictStr] = None
    virus3_ml_mm: Optional[StrictStr] = None
    virus3_dv_mm: Optional[StrictStr] = None
    virus3_dv_b_mm: Optional[StrictStr] = None
    virus3_stereotaxic_volume_injected_nl: Optional[StrictStr] = None
    virus4_injection_date: Optional[StrictStr] = None
    virus4_age_of_injection: Optional[StrictStr] = None
    virus4_injection_type: Optional[StrictStr] = None
    virus4: Optional[StrictStr] = None
    virus4_id: Optional[StrictStr] = None
    virus4_stock_titer_gc_ml: Optional[StrictStr] = None
    virus4_dose_gc: Optional[StrictStr] = None
    virus4_effective_titer_gc_ml: Optional[StrictStr] = None
    virus4_ap_mm: Optional[StrictStr] = None
    virus4_ml_mm: Optional[StrictStr] = None
    virus4_dv_mm: Optional[StrictStr] = None
    virus4_dv_b_mm: Optional[StrictStr] = None
    stereotaxic_volume_injected_nl: Optional[StrictStr] = None
    heparin_dose_u: Optional[StrictStr] = None
    perfused: Optional[StrictStr] = None
    perfusion_type: Optional[StrictStr] = None
    perfusion_date: Optional[StrictStr] = None
    age_of_perfusion: Optional[StrictStr] = None
    las_injection_notes: Optional[StrictStr] = None
    las_perfusion_dissection_notes: Optional[StrictStr] = None
    gross_anatomy_notes_pre_processing: Optional[StrictStr] = None
    other_notes: Optional[StrictStr] = None
    other_notes2: Optional[StrictStr] = None
    neuro_glancer_link: Optional[StrictStr] = None
    good_labeling_sparsity: Optional[StrictStr] = None
    target_area_of_interest: Optional[StrictStr] = None
    investigator: Optional[StrictStr] = None
    project_code: Optional[StrictStr] = None
    project_name: Optional[StrictStr] = None
    death_health_issues: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["num", "ex_m_processing_status", "status", "mouse_id", "sample_name", "workflow", "project_description", "expression_time_days", "pedigree", "sex", "dob", "stx_injection_requested", "ro_injection_requested", "perfusion_requested", "inj_details_tam_dose", "tam_dosing_last_day", "label", "virus_mix_ro", "virus_mix_total_volume_injected_ro_ul", "virus_mix_vehicle_ro", "virus1_injection_date", "virus1_age_of_injection", "virus1_injection_type", "virus1", "ai_p_num", "virus1_id", "virus1_stock_titer_gc_ml", "working_titer_gc_ml", "virus1_dose_gc", "virus1_ap_mm", "virus1_ml_mm", "virus1_dv_mm", "virus1_dv_b_mm", "virus1_stereotaxic_volume_injected_nl", "virus2_injection_date", "virus2_age_of_injection", "virus2_injection_type", "virus2", "virus2_ai_p_num", "virus2_id", "virus2_stock_titer_gc_ml", "virus2_working_titer_gc_ml", "virus2_dose_gc", "virus2_effective_titer_gc_ml", "virus2_ap_mm", "virus2_ml_mm", "virus2_dv_mm", "virus2_dv_b_mm", "virus2_stereotaxic_volume_injected_nl", "virus3_injection_date", "virus3_age_of_injection", "virus3_injection_type", "virus3", "virus3_ai_p_num", "virus3_id", "virus3_stock_titer_gc_ml", "virus3_dose_gc", "virus3_effective_titer_gc_ml", "virus3_ap_mm", "virus3_ml_mm", "virus3_dv_mm", "virus3_dv_b_mm", "virus3_stereotaxic_volume_injected_nl", "virus4_injection_date", "virus4_age_of_injection", "virus4_injection_type", "virus4", "virus4_id", "virus4_stock_titer_gc_ml", "virus4_dose_gc", "virus4_effective_titer_gc_ml", "virus4_ap_mm", "virus4_ml_mm", "virus4_dv_mm", "virus4_dv_b_mm", "stereotaxic_volume_injected_nl", "heparin_dose_u", "perfused", "perfusion_type", "perfusion_date", "age_of_perfusion", "las_injection_notes", "las_perfusion_dissection_notes", "gross_anatomy_notes_pre_processing", "other_notes", "other_notes2", "neuro_glancer_link", "good_labeling_sparsity", "target_area_of_interest", "investigator", "project_code", "project_name", "death_health_issues"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MouseTracker from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if ex_m_processing_status (nullable) is None
        # and model_fields_set contains the field
        if self.ex_m_processing_status is None and "ex_m_processing_status" in self.model_fields_set:
            _dict['ex_m_processing_status'] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        # set to None if mouse_id (nullable) is None
        # and model_fields_set contains the field
        if self.mouse_id is None and "mouse_id" in self.model_fields_set:
            _dict['mouse_id'] = None

        # set to None if sample_name (nullable) is None
        # and model_fields_set contains the field
        if self.sample_name is None and "sample_name" in self.model_fields_set:
            _dict['sample_name'] = None

        # set to None if workflow (nullable) is None
        # and model_fields_set contains the field
        if self.workflow is None and "workflow" in self.model_fields_set:
            _dict['workflow'] = None

        # set to None if project_description (nullable) is None
        # and model_fields_set contains the field
        if self.project_description is None and "project_description" in self.model_fields_set:
            _dict['project_description'] = None

        # set to None if expression_time_days (nullable) is None
        # and model_fields_set contains the field
        if self.expression_time_days is None and "expression_time_days" in self.model_fields_set:
            _dict['expression_time_days'] = None

        # set to None if pedigree (nullable) is None
        # and model_fields_set contains the field
        if self.pedigree is None and "pedigree" in self.model_fields_set:
            _dict['pedigree'] = None

        # set to None if sex (nullable) is None
        # and model_fields_set contains the field
        if self.sex is None and "sex" in self.model_fields_set:
            _dict['sex'] = None

        # set to None if dob (nullable) is None
        # and model_fields_set contains the field
        if self.dob is None and "dob" in self.model_fields_set:
            _dict['dob'] = None

        # set to None if stx_injection_requested (nullable) is None
        # and model_fields_set contains the field
        if self.stx_injection_requested is None and "stx_injection_requested" in self.model_fields_set:
            _dict['stx_injection_requested'] = None

        # set to None if ro_injection_requested (nullable) is None
        # and model_fields_set contains the field
        if self.ro_injection_requested is None and "ro_injection_requested" in self.model_fields_set:
            _dict['ro_injection_requested'] = None

        # set to None if perfusion_requested (nullable) is None
        # and model_fields_set contains the field
        if self.perfusion_requested is None and "perfusion_requested" in self.model_fields_set:
            _dict['perfusion_requested'] = None

        # set to None if inj_details_tam_dose (nullable) is None
        # and model_fields_set contains the field
        if self.inj_details_tam_dose is None and "inj_details_tam_dose" in self.model_fields_set:
            _dict['inj_details_tam_dose'] = None

        # set to None if tam_dosing_last_day (nullable) is None
        # and model_fields_set contains the field
        if self.tam_dosing_last_day is None and "tam_dosing_last_day" in self.model_fields_set:
            _dict['tam_dosing_last_day'] = None

        # set to None if label (nullable) is None
        # and model_fields_set contains the field
        if self.label is None and "label" in self.model_fields_set:
            _dict['label'] = None

        # set to None if virus_mix_ro (nullable) is None
        # and model_fields_set contains the field
        if self.virus_mix_ro is None and "virus_mix_ro" in self.model_fields_set:
            _dict['virus_mix_ro'] = None

        # set to None if virus_mix_total_volume_injected_ro_ul (nullable) is None
        # and model_fields_set contains the field
        if self.virus_mix_total_volume_injected_ro_ul is None and "virus_mix_total_volume_injected_ro_ul" in self.model_fields_set:
            _dict['virus_mix_total_volume_injected_ro_ul'] = None

        # set to None if virus_mix_vehicle_ro (nullable) is None
        # and model_fields_set contains the field
        if self.virus_mix_vehicle_ro is None and "virus_mix_vehicle_ro" in self.model_fields_set:
            _dict['virus_mix_vehicle_ro'] = None

        # set to None if virus1_injection_date (nullable) is None
        # and model_fields_set contains the field
        if self.virus1_injection_date is None and "virus1_injection_date" in self.model_fields_set:
            _dict['virus1_injection_date'] = None

        # set to None if virus1_age_of_injection (nullable) is None
        # and model_fields_set contains the field
        if self.virus1_age_of_injection is None and "virus1_age_of_injection" in self.model_fields_set:
            _dict['virus1_age_of_injection'] = None

        # set to None if virus1_injection_type (nullable) is None
        # and model_fields_set contains the field
        if self.virus1_injection_type is None and "virus1_injection_type" in self.model_fields_set:
            _dict['virus1_injection_type'] = None

        # set to None if virus1 (nullable) is None
        # and model_fields_set contains the field
        if self.virus1 is None and "virus1" in self.model_fields_set:
            _dict['virus1'] = None

        # set to None if ai_p_num (nullable) is None
        # and model_fields_set contains the field
        if self.ai_p_num is None and "ai_p_num" in self.model_fields_set:
            _dict['ai_p_num'] = None

        # set to None if virus1_id (nullable) is None
        # and model_fields_set contains the field
        if self.virus1_id is None and "virus1_id" in self.model_fields_set:
            _dict['virus1_id'] = None

        # set to None if virus1_stock_titer_gc_ml (nullable) is None
        # and model_fields_set contains the field
        if self.virus1_stock_titer_gc_ml is None and "virus1_stock_titer_gc_ml" in self.model_fields_set:
            _dict['virus1_stock_titer_gc_ml'] = None

        # set to None if working_titer_gc_ml (nullable) is None
        # and model_fields_set contains the field
        if self.working_titer_gc_ml is None and "working_titer_gc_ml" in self.model_fields_set:
            _dict['working_titer_gc_ml'] = None

        # set to None if virus1_dose_gc (nullable) is None
        # and model_fields_set contains the field
        if self.virus1_dose_gc is None and "virus1_dose_gc" in self.model_fields_set:
            _dict['virus1_dose_gc'] = None

        # set to None if virus1_ap_mm (nullable) is None
        # and model_fields_set contains the field
        if self.virus1_ap_mm is None and "virus1_ap_mm" in self.model_fields_set:
            _dict['virus1_ap_mm'] = None

        # set to None if virus1_ml_mm (nullable) is None
        # and model_fields_set contains the field
        if self.virus1_ml_mm is None and "virus1_ml_mm" in self.model_fields_set:
            _dict['virus1_ml_mm'] = None

        # set to None if virus1_dv_mm (nullable) is None
        # and model_fields_set contains the field
        if self.virus1_dv_mm is None and "virus1_dv_mm" in self.model_fields_set:
            _dict['virus1_dv_mm'] = None

        # set to None if virus1_dv_b_mm (nullable) is None
        # and model_fields_set contains the field
        if self.virus1_dv_b_mm is None and "virus1_dv_b_mm" in self.model_fields_set:
            _dict['virus1_dv_b_mm'] = None

        # set to None if virus1_stereotaxic_volume_injected_nl (nullable) is None
        # and model_fields_set contains the field
        if self.virus1_stereotaxic_volume_injected_nl is None and "virus1_stereotaxic_volume_injected_nl" in self.model_fields_set:
            _dict['virus1_stereotaxic_volume_injected_nl'] = None

        # set to None if virus2_injection_date (nullable) is None
        # and model_fields_set contains the field
        if self.virus2_injection_date is None and "virus2_injection_date" in self.model_fields_set:
            _dict['virus2_injection_date'] = None

        # set to None if virus2_age_of_injection (nullable) is None
        # and model_fields_set contains the field
        if self.virus2_age_of_injection is None and "virus2_age_of_injection" in self.model_fields_set:
            _dict['virus2_age_of_injection'] = None

        # set to None if virus2_injection_type (nullable) is None
        # and model_fields_set contains the field
        if self.virus2_injection_type is None and "virus2_injection_type" in self.model_fields_set:
            _dict['virus2_injection_type'] = None

        # set to None if virus2 (nullable) is None
        # and model_fields_set contains the field
        if self.virus2 is None and "virus2" in self.model_fields_set:
            _dict['virus2'] = None

        # set to None if virus2_ai_p_num (nullable) is None
        # and model_fields_set contains the field
        if self.virus2_ai_p_num is None and "virus2_ai_p_num" in self.model_fields_set:
            _dict['virus2_ai_p_num'] = None

        # set to None if virus2_id (nullable) is None
        # and model_fields_set contains the field
        if self.virus2_id is None and "virus2_id" in self.model_fields_set:
            _dict['virus2_id'] = None

        # set to None if virus2_stock_titer_gc_ml (nullable) is None
        # and model_fields_set contains the field
        if self.virus2_stock_titer_gc_ml is None and "virus2_stock_titer_gc_ml" in self.model_fields_set:
            _dict['virus2_stock_titer_gc_ml'] = None

        # set to None if virus2_working_titer_gc_ml (nullable) is None
        # and model_fields_set contains the field
        if self.virus2_working_titer_gc_ml is None and "virus2_working_titer_gc_ml" in self.model_fields_set:
            _dict['virus2_working_titer_gc_ml'] = None

        # set to None if virus2_dose_gc (nullable) is None
        # and model_fields_set contains the field
        if self.virus2_dose_gc is None and "virus2_dose_gc" in self.model_fields_set:
            _dict['virus2_dose_gc'] = None

        # set to None if virus2_effective_titer_gc_ml (nullable) is None
        # and model_fields_set contains the field
        if self.virus2_effective_titer_gc_ml is None and "virus2_effective_titer_gc_ml" in self.model_fields_set:
            _dict['virus2_effective_titer_gc_ml'] = None

        # set to None if virus2_ap_mm (nullable) is None
        # and model_fields_set contains the field
        if self.virus2_ap_mm is None and "virus2_ap_mm" in self.model_fields_set:
            _dict['virus2_ap_mm'] = None

        # set to None if virus2_ml_mm (nullable) is None
        # and model_fields_set contains the field
        if self.virus2_ml_mm is None and "virus2_ml_mm" in self.model_fields_set:
            _dict['virus2_ml_mm'] = None

        # set to None if virus2_dv_mm (nullable) is None
        # and model_fields_set contains the field
        if self.virus2_dv_mm is None and "virus2_dv_mm" in self.model_fields_set:
            _dict['virus2_dv_mm'] = None

        # set to None if virus2_dv_b_mm (nullable) is None
        # and model_fields_set contains the field
        if self.virus2_dv_b_mm is None and "virus2_dv_b_mm" in self.model_fields_set:
            _dict['virus2_dv_b_mm'] = None

        # set to None if virus2_stereotaxic_volume_injected_nl (nullable) is None
        # and model_fields_set contains the field
        if self.virus2_stereotaxic_volume_injected_nl is None and "virus2_stereotaxic_volume_injected_nl" in self.model_fields_set:
            _dict['virus2_stereotaxic_volume_injected_nl'] = None

        # set to None if virus3_injection_date (nullable) is None
        # and model_fields_set contains the field
        if self.virus3_injection_date is None and "virus3_injection_date" in self.model_fields_set:
            _dict['virus3_injection_date'] = None

        # set to None if virus3_age_of_injection (nullable) is None
        # and model_fields_set contains the field
        if self.virus3_age_of_injection is None and "virus3_age_of_injection" in self.model_fields_set:
            _dict['virus3_age_of_injection'] = None

        # set to None if virus3_injection_type (nullable) is None
        # and model_fields_set contains the field
        if self.virus3_injection_type is None and "virus3_injection_type" in self.model_fields_set:
            _dict['virus3_injection_type'] = None

        # set to None if virus3 (nullable) is None
        # and model_fields_set contains the field
        if self.virus3 is None and "virus3" in self.model_fields_set:
            _dict['virus3'] = None

        # set to None if virus3_ai_p_num (nullable) is None
        # and model_fields_set contains the field
        if self.virus3_ai_p_num is None and "virus3_ai_p_num" in self.model_fields_set:
            _dict['virus3_ai_p_num'] = None

        # set to None if virus3_id (nullable) is None
        # and model_fields_set contains the field
        if self.virus3_id is None and "virus3_id" in self.model_fields_set:
            _dict['virus3_id'] = None

        # set to None if virus3_stock_titer_gc_ml (nullable) is None
        # and model_fields_set contains the field
        if self.virus3_stock_titer_gc_ml is None and "virus3_stock_titer_gc_ml" in self.model_fields_set:
            _dict['virus3_stock_titer_gc_ml'] = None

        # set to None if virus3_dose_gc (nullable) is None
        # and model_fields_set contains the field
        if self.virus3_dose_gc is None and "virus3_dose_gc" in self.model_fields_set:
            _dict['virus3_dose_gc'] = None

        # set to None if virus3_effective_titer_gc_ml (nullable) is None
        # and model_fields_set contains the field
        if self.virus3_effective_titer_gc_ml is None and "virus3_effective_titer_gc_ml" in self.model_fields_set:
            _dict['virus3_effective_titer_gc_ml'] = None

        # set to None if virus3_ap_mm (nullable) is None
        # and model_fields_set contains the field
        if self.virus3_ap_mm is None and "virus3_ap_mm" in self.model_fields_set:
            _dict['virus3_ap_mm'] = None

        # set to None if virus3_ml_mm (nullable) is None
        # and model_fields_set contains the field
        if self.virus3_ml_mm is None and "virus3_ml_mm" in self.model_fields_set:
            _dict['virus3_ml_mm'] = None

        # set to None if virus3_dv_mm (nullable) is None
        # and model_fields_set contains the field
        if self.virus3_dv_mm is None and "virus3_dv_mm" in self.model_fields_set:
            _dict['virus3_dv_mm'] = None

        # set to None if virus3_dv_b_mm (nullable) is None
        # and model_fields_set contains the field
        if self.virus3_dv_b_mm is None and "virus3_dv_b_mm" in self.model_fields_set:
            _dict['virus3_dv_b_mm'] = None

        # set to None if virus3_stereotaxic_volume_injected_nl (nullable) is None
        # and model_fields_set contains the field
        if self.virus3_stereotaxic_volume_injected_nl is None and "virus3_stereotaxic_volume_injected_nl" in self.model_fields_set:
            _dict['virus3_stereotaxic_volume_injected_nl'] = None

        # set to None if virus4_injection_date (nullable) is None
        # and model_fields_set contains the field
        if self.virus4_injection_date is None and "virus4_injection_date" in self.model_fields_set:
            _dict['virus4_injection_date'] = None

        # set to None if virus4_age_of_injection (nullable) is None
        # and model_fields_set contains the field
        if self.virus4_age_of_injection is None and "virus4_age_of_injection" in self.model_fields_set:
            _dict['virus4_age_of_injection'] = None

        # set to None if virus4_injection_type (nullable) is None
        # and model_fields_set contains the field
        if self.virus4_injection_type is None and "virus4_injection_type" in self.model_fields_set:
            _dict['virus4_injection_type'] = None

        # set to None if virus4 (nullable) is None
        # and model_fields_set contains the field
        if self.virus4 is None and "virus4" in self.model_fields_set:
            _dict['virus4'] = None

        # set to None if virus4_id (nullable) is None
        # and model_fields_set contains the field
        if self.virus4_id is None and "virus4_id" in self.model_fields_set:
            _dict['virus4_id'] = None

        # set to None if virus4_stock_titer_gc_ml (nullable) is None
        # and model_fields_set contains the field
        if self.virus4_stock_titer_gc_ml is None and "virus4_stock_titer_gc_ml" in self.model_fields_set:
            _dict['virus4_stock_titer_gc_ml'] = None

        # set to None if virus4_dose_gc (nullable) is None
        # and model_fields_set contains the field
        if self.virus4_dose_gc is None and "virus4_dose_gc" in self.model_fields_set:
            _dict['virus4_dose_gc'] = None

        # set to None if virus4_effective_titer_gc_ml (nullable) is None
        # and model_fields_set contains the field
        if self.virus4_effective_titer_gc_ml is None and "virus4_effective_titer_gc_ml" in self.model_fields_set:
            _dict['virus4_effective_titer_gc_ml'] = None

        # set to None if virus4_ap_mm (nullable) is None
        # and model_fields_set contains the field
        if self.virus4_ap_mm is None and "virus4_ap_mm" in self.model_fields_set:
            _dict['virus4_ap_mm'] = None

        # set to None if virus4_ml_mm (nullable) is None
        # and model_fields_set contains the field
        if self.virus4_ml_mm is None and "virus4_ml_mm" in self.model_fields_set:
            _dict['virus4_ml_mm'] = None

        # set to None if virus4_dv_mm (nullable) is None
        # and model_fields_set contains the field
        if self.virus4_dv_mm is None and "virus4_dv_mm" in self.model_fields_set:
            _dict['virus4_dv_mm'] = None

        # set to None if virus4_dv_b_mm (nullable) is None
        # and model_fields_set contains the field
        if self.virus4_dv_b_mm is None and "virus4_dv_b_mm" in self.model_fields_set:
            _dict['virus4_dv_b_mm'] = None

        # set to None if stereotaxic_volume_injected_nl (nullable) is None
        # and model_fields_set contains the field
        if self.stereotaxic_volume_injected_nl is None and "stereotaxic_volume_injected_nl" in self.model_fields_set:
            _dict['stereotaxic_volume_injected_nl'] = None

        # set to None if heparin_dose_u (nullable) is None
        # and model_fields_set contains the field
        if self.heparin_dose_u is None and "heparin_dose_u" in self.model_fields_set:
            _dict['heparin_dose_u'] = None

        # set to None if perfused (nullable) is None
        # and model_fields_set contains the field
        if self.perfused is None and "perfused" in self.model_fields_set:
            _dict['perfused'] = None

        # set to None if perfusion_type (nullable) is None
        # and model_fields_set contains the field
        if self.perfusion_type is None and "perfusion_type" in self.model_fields_set:
            _dict['perfusion_type'] = None

        # set to None if perfusion_date (nullable) is None
        # and model_fields_set contains the field
        if self.perfusion_date is None and "perfusion_date" in self.model_fields_set:
            _dict['perfusion_date'] = None

        # set to None if age_of_perfusion (nullable) is None
        # and model_fields_set contains the field
        if self.age_of_perfusion is None and "age_of_perfusion" in self.model_fields_set:
            _dict['age_of_perfusion'] = None

        # set to None if las_injection_notes (nullable) is None
        # and model_fields_set contains the field
        if self.las_injection_notes is None and "las_injection_notes" in self.model_fields_set:
            _dict['las_injection_notes'] = None

        # set to None if las_perfusion_dissection_notes (nullable) is None
        # and model_fields_set contains the field
        if self.las_perfusion_dissection_notes is None and "las_perfusion_dissection_notes" in self.model_fields_set:
            _dict['las_perfusion_dissection_notes'] = None

        # set to None if gross_anatomy_notes_pre_processing (nullable) is None
        # and model_fields_set contains the field
        if self.gross_anatomy_notes_pre_processing is None and "gross_anatomy_notes_pre_processing" in self.model_fields_set:
            _dict['gross_anatomy_notes_pre_processing'] = None

        # set to None if other_notes (nullable) is None
        # and model_fields_set contains the field
        if self.other_notes is None and "other_notes" in self.model_fields_set:
            _dict['other_notes'] = None

        # set to None if other_notes2 (nullable) is None
        # and model_fields_set contains the field
        if self.other_notes2 is None and "other_notes2" in self.model_fields_set:
            _dict['other_notes2'] = None

        # set to None if neuro_glancer_link (nullable) is None
        # and model_fields_set contains the field
        if self.neuro_glancer_link is None and "neuro_glancer_link" in self.model_fields_set:
            _dict['neuro_glancer_link'] = None

        # set to None if good_labeling_sparsity (nullable) is None
        # and model_fields_set contains the field
        if self.good_labeling_sparsity is None and "good_labeling_sparsity" in self.model_fields_set:
            _dict['good_labeling_sparsity'] = None

        # set to None if target_area_of_interest (nullable) is None
        # and model_fields_set contains the field
        if self.target_area_of_interest is None and "target_area_of_interest" in self.model_fields_set:
            _dict['target_area_of_interest'] = None

        # set to None if investigator (nullable) is None
        # and model_fields_set contains the field
        if self.investigator is None and "investigator" in self.model_fields_set:
            _dict['investigator'] = None

        # set to None if project_code (nullable) is None
        # and model_fields_set contains the field
        if self.project_code is None and "project_code" in self.model_fields_set:
            _dict['project_code'] = None

        # set to None if project_name (nullable) is None
        # and model_fields_set contains the field
        if self.project_name is None and "project_name" in self.model_fields_set:
            _dict['project_name'] = None

        # set to None if death_health_issues (nullable) is None
        # and model_fields_set contains the field
        if self.death_health_issues is None and "death_health_issues" in self.model_fields_set:
            _dict['death_health_issues'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MouseTracker from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "num": obj.get("num"),
            "ex_m_processing_status": obj.get("ex_m_processing_status"),
            "status": obj.get("status"),
            "mouse_id": obj.get("mouse_id"),
            "sample_name": obj.get("sample_name"),
            "workflow": obj.get("workflow"),
            "project_description": obj.get("project_description"),
            "expression_time_days": obj.get("expression_time_days"),
            "pedigree": obj.get("pedigree"),
            "sex": obj.get("sex"),
            "dob": obj.get("dob"),
            "stx_injection_requested": obj.get("stx_injection_requested"),
            "ro_injection_requested": obj.get("ro_injection_requested"),
            "perfusion_requested": obj.get("perfusion_requested"),
            "inj_details_tam_dose": obj.get("inj_details_tam_dose"),
            "tam_dosing_last_day": obj.get("tam_dosing_last_day"),
            "label": obj.get("label"),
            "virus_mix_ro": obj.get("virus_mix_ro"),
            "virus_mix_total_volume_injected_ro_ul": obj.get("virus_mix_total_volume_injected_ro_ul"),
            "virus_mix_vehicle_ro": obj.get("virus_mix_vehicle_ro"),
            "virus1_injection_date": obj.get("virus1_injection_date"),
            "virus1_age_of_injection": obj.get("virus1_age_of_injection"),
            "virus1_injection_type": obj.get("virus1_injection_type"),
            "virus1": obj.get("virus1"),
            "ai_p_num": obj.get("ai_p_num"),
            "virus1_id": obj.get("virus1_id"),
            "virus1_stock_titer_gc_ml": obj.get("virus1_stock_titer_gc_ml"),
            "working_titer_gc_ml": obj.get("working_titer_gc_ml"),
            "virus1_dose_gc": obj.get("virus1_dose_gc"),
            "virus1_ap_mm": obj.get("virus1_ap_mm"),
            "virus1_ml_mm": obj.get("virus1_ml_mm"),
            "virus1_dv_mm": obj.get("virus1_dv_mm"),
            "virus1_dv_b_mm": obj.get("virus1_dv_b_mm"),
            "virus1_stereotaxic_volume_injected_nl": obj.get("virus1_stereotaxic_volume_injected_nl"),
            "virus2_injection_date": obj.get("virus2_injection_date"),
            "virus2_age_of_injection": obj.get("virus2_age_of_injection"),
            "virus2_injection_type": obj.get("virus2_injection_type"),
            "virus2": obj.get("virus2"),
            "virus2_ai_p_num": obj.get("virus2_ai_p_num"),
            "virus2_id": obj.get("virus2_id"),
            "virus2_stock_titer_gc_ml": obj.get("virus2_stock_titer_gc_ml"),
            "virus2_working_titer_gc_ml": obj.get("virus2_working_titer_gc_ml"),
            "virus2_dose_gc": obj.get("virus2_dose_gc"),
            "virus2_effective_titer_gc_ml": obj.get("virus2_effective_titer_gc_ml"),
            "virus2_ap_mm": obj.get("virus2_ap_mm"),
            "virus2_ml_mm": obj.get("virus2_ml_mm"),
            "virus2_dv_mm": obj.get("virus2_dv_mm"),
            "virus2_dv_b_mm": obj.get("virus2_dv_b_mm"),
            "virus2_stereotaxic_volume_injected_nl": obj.get("virus2_stereotaxic_volume_injected_nl"),
            "virus3_injection_date": obj.get("virus3_injection_date"),
            "virus3_age_of_injection": obj.get("virus3_age_of_injection"),
            "virus3_injection_type": obj.get("virus3_injection_type"),
            "virus3": obj.get("virus3"),
            "virus3_ai_p_num": obj.get("virus3_ai_p_num"),
            "virus3_id": obj.get("virus3_id"),
            "virus3_stock_titer_gc_ml": obj.get("virus3_stock_titer_gc_ml"),
            "virus3_dose_gc": obj.get("virus3_dose_gc"),
            "virus3_effective_titer_gc_ml": obj.get("virus3_effective_titer_gc_ml"),
            "virus3_ap_mm": obj.get("virus3_ap_mm"),
            "virus3_ml_mm": obj.get("virus3_ml_mm"),
            "virus3_dv_mm": obj.get("virus3_dv_mm"),
            "virus3_dv_b_mm": obj.get("virus3_dv_b_mm"),
            "virus3_stereotaxic_volume_injected_nl": obj.get("virus3_stereotaxic_volume_injected_nl"),
            "virus4_injection_date": obj.get("virus4_injection_date"),
            "virus4_age_of_injection": obj.get("virus4_age_of_injection"),
            "virus4_injection_type": obj.get("virus4_injection_type"),
            "virus4": obj.get("virus4"),
            "virus4_id": obj.get("virus4_id"),
            "virus4_stock_titer_gc_ml": obj.get("virus4_stock_titer_gc_ml"),
            "virus4_dose_gc": obj.get("virus4_dose_gc"),
            "virus4_effective_titer_gc_ml": obj.get("virus4_effective_titer_gc_ml"),
            "virus4_ap_mm": obj.get("virus4_ap_mm"),
            "virus4_ml_mm": obj.get("virus4_ml_mm"),
            "virus4_dv_mm": obj.get("virus4_dv_mm"),
            "virus4_dv_b_mm": obj.get("virus4_dv_b_mm"),
            "stereotaxic_volume_injected_nl": obj.get("stereotaxic_volume_injected_nl"),
            "heparin_dose_u": obj.get("heparin_dose_u"),
            "perfused": obj.get("perfused"),
            "perfusion_type": obj.get("perfusion_type"),
            "perfusion_date": obj.get("perfusion_date"),
            "age_of_perfusion": obj.get("age_of_perfusion"),
            "las_injection_notes": obj.get("las_injection_notes"),
            "las_perfusion_dissection_notes": obj.get("las_perfusion_dissection_notes"),
            "gross_anatomy_notes_pre_processing": obj.get("gross_anatomy_notes_pre_processing"),
            "other_notes": obj.get("other_notes"),
            "other_notes2": obj.get("other_notes2"),
            "neuro_glancer_link": obj.get("neuro_glancer_link"),
            "good_labeling_sparsity": obj.get("good_labeling_sparsity"),
            "target_area_of_interest": obj.get("target_area_of_interest"),
            "investigator": obj.get("investigator"),
            "project_code": obj.get("project_code"),
            "project_name": obj.get("project_name"),
            "death_health_issues": obj.get("death_health_issues")
        })
        return _obj


