# coding: utf-8

"""
    aind-smartsheet-service

     ## aind-smartsheet-service  Service to pull data from SmartSheet.  

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class PerfusionsModel(BaseModel):
    """
    Expected model for the Perfusions SmartSheet
    """ # noqa: E501
    subject_id: Optional[StrictStr] = None
    var_date: Optional[date] = Field(default=None, alias="date")
    experimenter: Optional[StrictStr] = None
    iacuc_protocol: Optional[StrictStr] = None
    animal_weight_prior: Optional[StrictStr] = None
    output_specimen_id: Optional[StrictStr] = None
    postfix_solution: Optional[StrictStr] = None
    notes: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["subject_id", "date", "experimenter", "iacuc_protocol", "animal_weight_prior", "output_specimen_id", "postfix_solution", "notes"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PerfusionsModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if subject_id (nullable) is None
        # and model_fields_set contains the field
        if self.subject_id is None and "subject_id" in self.model_fields_set:
            _dict['subject_id'] = None

        # set to None if var_date (nullable) is None
        # and model_fields_set contains the field
        if self.var_date is None and "var_date" in self.model_fields_set:
            _dict['date'] = None

        # set to None if experimenter (nullable) is None
        # and model_fields_set contains the field
        if self.experimenter is None and "experimenter" in self.model_fields_set:
            _dict['experimenter'] = None

        # set to None if iacuc_protocol (nullable) is None
        # and model_fields_set contains the field
        if self.iacuc_protocol is None and "iacuc_protocol" in self.model_fields_set:
            _dict['iacuc_protocol'] = None

        # set to None if animal_weight_prior (nullable) is None
        # and model_fields_set contains the field
        if self.animal_weight_prior is None and "animal_weight_prior" in self.model_fields_set:
            _dict['animal_weight_prior'] = None

        # set to None if output_specimen_id (nullable) is None
        # and model_fields_set contains the field
        if self.output_specimen_id is None and "output_specimen_id" in self.model_fields_set:
            _dict['output_specimen_id'] = None

        # set to None if postfix_solution (nullable) is None
        # and model_fields_set contains the field
        if self.postfix_solution is None and "postfix_solution" in self.model_fields_set:
            _dict['postfix_solution'] = None

        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict['notes'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PerfusionsModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "subject_id": obj.get("subject_id"),
            "date": obj.get("date"),
            "experimenter": obj.get("experimenter"),
            "iacuc_protocol": obj.get("iacuc_protocol"),
            "animal_weight_prior": obj.get("animal_weight_prior"),
            "output_specimen_id": obj.get("output_specimen_id"),
            "postfix_solution": obj.get("postfix_solution"),
            "notes": obj.get("notes")
        })
        return _obj


