# coding: utf-8

"""
    aind-smartsheet-service

     ## aind-smartsheet-service  Service to pull data from SmartSheet.  

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_smartsheet_service_client.models.sample_tracking import SampleTracking

class TestSampleTracking(unittest.TestCase):
    """SampleTracking unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SampleTracking:
        """Test SampleTracking
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SampleTracking`
        """
        model = SampleTracking()
        if include_optional:
            return SampleTracking(
                external_sample = '',
                screening_status = '',
                status = '',
                sample = '',
                genotype = '',
                processing_lead = '',
                project = '',
                project_description = '',
                project_name = '',
                label = '',
                age_of_injection = '',
                virus_dose = '',
                dcm_delipidation_start = '',
                dcm_delipidation_end = '',
                sbip_delipidation_start = '',
                sbip_delipidation_end = '',
                immuno_primary_ab_start_date = '',
                immuno_primary_antibody1 = '',
                mass_of_primary_antibody1_used_per_brain_ug = '',
                primary_antibody1_catalog_num = '',
                primary_antibody1_lot_num = '',
                immuno_primary_antibody2 = '',
                mass_of_primary_antibody2_used_per_brain_ug = '',
                primary_antibody2_catalog_num = '',
                primary_antibody2_lot_num = '',
                immuno_primary_antibody3 = '',
                mass_of_primary_antibody3_used_per_brain_ug = '',
                primary_antibody3_catalog_num = '',
                primary_antibody3_lot_num = '',
                primary_antibody_rrid = '',
                immuno_secondary_ab_start_date = '',
                immuno_secondary_antibody1 = '',
                mass_of_secondary_antibody1_used_per_brain_ug = '',
                secondary_antibody1_catalog_num = '',
                secondary_antibody1_lot_num = '',
                immuno_secondary_antibody2 = '',
                mass_of_secondary_antibody2_used_per_brain_ug = '',
                secondary_antibody2_catalog_num = '',
                secondary_antibody2_lot_num = '',
                immuno_secondary_antibody3 = '',
                mass_of_secondary_antibody3_used_per_brain_ug = '',
                secondary_antibody3_catalog_num = '',
                secondary_antibody3_lot_num = '',
                secondary_antibody_rrid = '',
                fluorophore1 = '',
                fluorophore2 = '',
                fluorophore3 = '',
                fluorophore_t = '',
                gelation_mbs_start = '',
                gelation_mbs_end = '',
                gelation_ac_x_start = '',
                gelation_ac_x_end = '',
                gelation_pbs_wash_start = '',
                gelation_pbs_wash_end = '',
                gelation_stock_xva_044_equilibration_start = '',
                gelation_stock_xva_044_equilibration_end = '',
                gelation_prok_rt_start = '',
                gelation_prok_rt_end = '',
                duration_days = '',
                gelation_add_l_prok_37c_start = '',
                gelation_add_l_prok_37c_end = '',
                duration_days_gelation_add_l_prok_37c = '',
                pbs_wash_start = '',
                pbs_wash_end = '',
                date_of_storage_in_pbs_az_0_05_4c = '',
                notes = '',
                notes_ii = '',
                notes_iii = ''
            )
        else:
            return SampleTracking(
        )
        """

    def testSampleTracking(self):
        """Test SampleTracking"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
