# coding: utf-8

"""
    aind-smartsheet-service

     ## aind-smartsheet-service  Service to pull data from SmartSheet.  

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_smartsheet_service_client.models.qc_sheet import QcSheet

class TestQcSheet(unittest.TestCase):
    """QcSheet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QcSheet:
        """Test QcSheet
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QcSheet`
        """
        model = QcSheet()
        if include_optional:
            return QcSheet(
                sample = '',
                imaging_priority = '',
                date_sent_for_1x_imaging = '',
                date_of_tissue_processing_completion = '',
                status = '',
                genotype = '',
                label = '',
                project_description = '',
                perfusion_date = '',
                las_injection_notes = '',
                las_perfusion_dissection_notes = '',
                perfusion_dissection_quality_notes = '',
                perfusion_pass_fail = '',
                labeling_density_notes_olympus_mxv10 = '',
                durotomy_tissue_damage_notes = '',
                immuno_gross_anatomy_notes = '',
                immuno_pass_fail = '',
                digestion_notes = '',
                digestion_pass_fail = '',
                special_notes = '',
                brain_size_at_1x_imaging = '',
                one_x_screening_link = '',
                investigator = '',
                project_name = '',
                surface_labeling = '',
                vascular_labeling = '',
                no_artifacts = '',
                targeted_sparsity = '',
                no_surface_labeling = '',
                no_vascular_labeling = '',
                targeted_sparsity_q = '',
                one_x_review_pass_fail = '',
                one_x_screening_notes_platform_lead = '',
                one_x_screening_notes_sample_processing_r_a = '',
                one_x_screening_notes_investigator = '',
                five_x_imaging_date = ''
            )
        else:
            return QcSheet(
        )
        """

    def testQcSheet(self):
        """Test QcSheet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
