# coding: utf-8

"""
    aind-smartsheet-service

     ## aind-smartsheet-service  Service to pull data from SmartSheet.  

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_smartsheet_service_async_client.models.exa_spim_info import ExaSPIMInfo

class TestExaSPIMInfo(unittest.TestCase):
    """ExaSPIMInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExaSPIMInfo:
        """Test ExaSPIMInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExaSPIMInfo`
        """
        model = ExaSPIMInfo()
        if include_optional:
            return ExaSPIMInfo(
                mouse_tracker_info = [
                    aind_smartsheet_service_async_client.models.mouse_tracker.MouseTracker(
                        num = 56, 
                        ex_m_processing_status = '', 
                        status = '', 
                        mouse_id = '', 
                        sample_name = '', 
                        workflow = '', 
                        project_description = '', 
                        expression_time_days = '', 
                        pedigree = '', 
                        sex = '', 
                        dob = '', 
                        stx_injection_requested = '', 
                        ro_injection_requested = '', 
                        perfusion_requested = '', 
                        inj_details_tam_dose = '', 
                        tam_dosing_last_day = '', 
                        label = '', 
                        virus_mix_ro = '', 
                        virus_mix_total_volume_injected_ro_ul = '', 
                        virus_mix_vehicle_ro = '', 
                        virus1_injection_date = '', 
                        virus1_age_of_injection = '', 
                        virus1_injection_type = '', 
                        virus1 = '', 
                        ai_p_num = '', 
                        virus1_id = '', 
                        virus1_stock_titer_gc_ml = '', 
                        working_titer_gc_ml = '', 
                        virus1_dose_gc = '', 
                        virus1_ap_mm = '', 
                        virus1_ml_mm = '', 
                        virus1_dv_mm = '', 
                        virus1_dv_b_mm = '', 
                        virus1_stereotaxic_volume_injected_nl = '', 
                        virus2_injection_date = '', 
                        virus2_age_of_injection = '', 
                        virus2_injection_type = '', 
                        virus2 = '', 
                        virus2_ai_p_num = '', 
                        virus2_id = '', 
                        virus2_stock_titer_gc_ml = '', 
                        virus2_working_titer_gc_ml = '', 
                        virus2_dose_gc = '', 
                        virus2_effective_titer_gc_ml = '', 
                        virus2_ap_mm = '', 
                        virus2_ml_mm = '', 
                        virus2_dv_mm = '', 
                        virus2_dv_b_mm = '', 
                        virus2_stereotaxic_volume_injected_nl = '', 
                        virus3_injection_date = '', 
                        virus3_age_of_injection = '', 
                        virus3_injection_type = '', 
                        virus3 = '', 
                        virus3_ai_p_num = '', 
                        virus3_id = '', 
                        virus3_stock_titer_gc_ml = '', 
                        virus3_dose_gc = '', 
                        virus3_effective_titer_gc_ml = '', 
                        virus3_ap_mm = '', 
                        virus3_ml_mm = '', 
                        virus3_dv_mm = '', 
                        virus3_dv_b_mm = '', 
                        virus3_stereotaxic_volume_injected_nl = '', 
                        virus4_injection_date = '', 
                        virus4_age_of_injection = '', 
                        virus4_injection_type = '', 
                        virus4 = '', 
                        virus4_id = '', 
                        virus4_stock_titer_gc_ml = '', 
                        virus4_dose_gc = '', 
                        virus4_effective_titer_gc_ml = '', 
                        virus4_ap_mm = '', 
                        virus4_ml_mm = '', 
                        virus4_dv_mm = '', 
                        virus4_dv_b_mm = '', 
                        stereotaxic_volume_injected_nl = '', 
                        heparin_dose_u = '', 
                        perfused = '', 
                        perfusion_type = '', 
                        perfusion_date = '', 
                        age_of_perfusion = '', 
                        las_injection_notes = '', 
                        las_perfusion_dissection_notes = '', 
                        gross_anatomy_notes_pre_processing = '', 
                        other_notes = '', 
                        other_notes2 = '', 
                        neuro_glancer_link = '', 
                        good_labeling_sparsity = '', 
                        target_area_of_interest = '', 
                        investigator = '', 
                        project_code = '', 
                        project_name = '', 
                        death_health_issues = '', )
                    ],
                sample_tracking_info = [
                    aind_smartsheet_service_async_client.models.sample_tracking.SampleTracking(
                        external_sample = '', 
                        screening_status = '', 
                        status = '', 
                        sample = '', 
                        genotype = '', 
                        processing_lead = '', 
                        project = '', 
                        project_description = '', 
                        project_name = '', 
                        label = '', 
                        age_of_injection = '', 
                        virus_dose = '', 
                        dcm_delipidation_start = '', 
                        dcm_delipidation_end = '', 
                        sbip_delipidation_start = '', 
                        sbip_delipidation_end = '', 
                        immuno_primary_ab_start_date = '', 
                        immuno_primary_antibody1 = '', 
                        mass_of_primary_antibody1_used_per_brain_ug = '', 
                        primary_antibody1_catalog_num = '', 
                        primary_antibody1_lot_num = '', 
                        immuno_primary_antibody2 = '', 
                        mass_of_primary_antibody2_used_per_brain_ug = '', 
                        primary_antibody2_catalog_num = '', 
                        primary_antibody2_lot_num = '', 
                        immuno_primary_antibody3 = '', 
                        mass_of_primary_antibody3_used_per_brain_ug = '', 
                        primary_antibody3_catalog_num = '', 
                        primary_antibody3_lot_num = '', 
                        primary_antibody_rrid = '', 
                        immuno_secondary_ab_start_date = '', 
                        immuno_secondary_antibody1 = '', 
                        mass_of_secondary_antibody1_used_per_brain_ug = '', 
                        secondary_antibody1_catalog_num = '', 
                        secondary_antibody1_lot_num = '', 
                        immuno_secondary_antibody2 = '', 
                        mass_of_secondary_antibody2_used_per_brain_ug = '', 
                        secondary_antibody2_catalog_num = '', 
                        secondary_antibody2_lot_num = '', 
                        immuno_secondary_antibody3 = '', 
                        mass_of_secondary_antibody3_used_per_brain_ug = '', 
                        secondary_antibody3_catalog_num = '', 
                        secondary_antibody3_lot_num = '', 
                        secondary_antibody_rrid = '', 
                        fluorophore1 = '', 
                        fluorophore2 = '', 
                        fluorophore3 = '', 
                        fluorophore_t = '', 
                        gelation_mbs_start = '', 
                        gelation_mbs_end = '', 
                        gelation_ac_x_start = '', 
                        gelation_ac_x_end = '', 
                        gelation_pbs_wash_start = '', 
                        gelation_pbs_wash_end = '', 
                        gelation_stock_xva_044_equilibration_start = '', 
                        gelation_stock_xva_044_equilibration_end = '', 
                        gelation_prok_rt_start = '', 
                        gelation_prok_rt_end = '', 
                        duration_days = '', 
                        gelation_add_l_prok_37c_start = '', 
                        gelation_add_l_prok_37c_end = '', 
                        duration_days_gelation_add_l_prok_37c = '', 
                        pbs_wash_start = '', 
                        pbs_wash_end = '', 
                        date_of_storage_in_pbs_az_0_05_4c = '', 
                        notes = '', 
                        notes_ii = '', 
                        notes_iii = '', )
                    ],
                imaging_queue_info = [
                    aind_smartsheet_service_async_client.models.imaging_queue.ImagingQueue(
                        count = '', 
                        sample = '', 
                        one_x_imaging_date = '', 
                        imaging_start_date = '', 
                        imaging_start_time = '', 
                        drop_off_date = '', 
                        imaging_end_date = '', 
                        imaging_end_time = '', 
                        imaging_buffer = '', 
                        microscope = '', 
                        status = '', 
                        genotype = '', 
                        label = '', 
                        fluorophore = '', 
                        signal_channel_s = '', 
                        auto_fluorescence_channel_s = '', 
                        focus_n_mm = '', 
                        etl_offset = '', 
                        notes = '', 
                        notes_1 = '', 
                        verified_mouse_tracker_for_metadata_intake = '', 
                        notes_on_missing_metadata = '', )
                    ],
                qc_sheet_info = [
                    aind_smartsheet_service_async_client.models.qc_sheet.QcSheet(
                        sample = '', 
                        imaging_priority = '', 
                        date_sent_for_1x_imaging = '', 
                        date_of_tissue_processing_completion = '', 
                        status = '', 
                        genotype = '', 
                        label = '', 
                        project_description = '', 
                        perfusion_date = '', 
                        las_injection_notes = '', 
                        las_perfusion_dissection_notes = '', 
                        perfusion_dissection_quality_notes = '', 
                        perfusion_pass_fail = '', 
                        labeling_density_notes_olympus_mxv10 = '', 
                        durotomy_tissue_damage_notes = '', 
                        immuno_gross_anatomy_notes = '', 
                        immuno_pass_fail = '', 
                        digestion_notes = '', 
                        digestion_pass_fail = '', 
                        special_notes = '', 
                        brain_size_at_1x_imaging = '', 
                        one_x_screening_link = '', 
                        investigator = '', 
                        project_name = '', 
                        surface_labeling = '', 
                        vascular_labeling = '', 
                        no_artifacts = '', 
                        targeted_sparsity = '', 
                        no_surface_labeling = '', 
                        no_vascular_labeling = '', 
                        targeted_sparsity_q = '', 
                        one_x_review_pass_fail = '', 
                        one_x_screening_notes_platform_lead = '', 
                        one_x_screening_notes_sample_processing_r_a = '', 
                        one_x_screening_notes_investigator = '', 
                        five_x_imaging_date = '', )
                    ]
            )
        else:
            return ExaSPIMInfo(
        )
        """

    def testExaSPIMInfo(self):
        """Test ExaSPIMInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
