# coding: utf-8

"""
    aind-smartsheet-service

     ## aind-smartsheet-service  Service to pull data from SmartSheet.  

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_smartsheet_service_async_client.models.mouse_tracker import MouseTracker

class TestMouseTracker(unittest.TestCase):
    """MouseTracker unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MouseTracker:
        """Test MouseTracker
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MouseTracker`
        """
        model = MouseTracker()
        if include_optional:
            return MouseTracker(
                num = 56,
                ex_m_processing_status = '',
                status = '',
                mouse_id = '',
                sample_name = '',
                workflow = '',
                project_description = '',
                expression_time_days = '',
                pedigree = '',
                sex = '',
                dob = '',
                stx_injection_requested = '',
                ro_injection_requested = '',
                perfusion_requested = '',
                inj_details_tam_dose = '',
                tam_dosing_last_day = '',
                label = '',
                virus_mix_ro = '',
                virus_mix_total_volume_injected_ro_ul = '',
                virus_mix_vehicle_ro = '',
                virus1_injection_date = '',
                virus1_age_of_injection = '',
                virus1_injection_type = '',
                virus1 = '',
                ai_p_num = '',
                virus1_id = '',
                virus1_stock_titer_gc_ml = '',
                working_titer_gc_ml = '',
                virus1_dose_gc = '',
                virus1_ap_mm = '',
                virus1_ml_mm = '',
                virus1_dv_mm = '',
                virus1_dv_b_mm = '',
                virus1_stereotaxic_volume_injected_nl = '',
                virus2_injection_date = '',
                virus2_age_of_injection = '',
                virus2_injection_type = '',
                virus2 = '',
                virus2_ai_p_num = '',
                virus2_id = '',
                virus2_stock_titer_gc_ml = '',
                virus2_working_titer_gc_ml = '',
                virus2_dose_gc = '',
                virus2_effective_titer_gc_ml = '',
                virus2_ap_mm = '',
                virus2_ml_mm = '',
                virus2_dv_mm = '',
                virus2_dv_b_mm = '',
                virus2_stereotaxic_volume_injected_nl = '',
                virus3_injection_date = '',
                virus3_age_of_injection = '',
                virus3_injection_type = '',
                virus3 = '',
                virus3_ai_p_num = '',
                virus3_id = '',
                virus3_stock_titer_gc_ml = '',
                virus3_dose_gc = '',
                virus3_effective_titer_gc_ml = '',
                virus3_ap_mm = '',
                virus3_ml_mm = '',
                virus3_dv_mm = '',
                virus3_dv_b_mm = '',
                virus3_stereotaxic_volume_injected_nl = '',
                virus4_injection_date = '',
                virus4_age_of_injection = '',
                virus4_injection_type = '',
                virus4 = '',
                virus4_id = '',
                virus4_stock_titer_gc_ml = '',
                virus4_dose_gc = '',
                virus4_effective_titer_gc_ml = '',
                virus4_ap_mm = '',
                virus4_ml_mm = '',
                virus4_dv_mm = '',
                virus4_dv_b_mm = '',
                stereotaxic_volume_injected_nl = '',
                heparin_dose_u = '',
                perfused = '',
                perfusion_type = '',
                perfusion_date = '',
                age_of_perfusion = '',
                las_injection_notes = '',
                las_perfusion_dissection_notes = '',
                gross_anatomy_notes_pre_processing = '',
                other_notes = '',
                other_notes2 = '',
                neuro_glancer_link = '',
                good_labeling_sparsity = '',
                target_area_of_interest = '',
                investigator = '',
                project_code = '',
                project_name = '',
                death_health_issues = ''
            )
        else:
            return MouseTracker(
                num = 56,
        )
        """

    def testMouseTracker(self):
        """Test MouseTracker"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
