# coding: utf-8

"""
    aind-smartsheet-service

     ## aind-smartsheet-service  Service to pull data from SmartSheet.  

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_smartsheet_service_async_client.models.imaging_queue import ImagingQueue

class TestImagingQueue(unittest.TestCase):
    """ImagingQueue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImagingQueue:
        """Test ImagingQueue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImagingQueue`
        """
        model = ImagingQueue()
        if include_optional:
            return ImagingQueue(
                count = '',
                sample = '',
                one_x_imaging_date = '',
                imaging_start_date = '',
                imaging_start_time = '',
                drop_off_date = '',
                imaging_end_date = '',
                imaging_end_time = '',
                imaging_buffer = '',
                microscope = '',
                status = '',
                genotype = '',
                label = '',
                fluorophore = '',
                signal_channel_s = '',
                auto_fluorescence_channel_s = '',
                focus_n_mm = '',
                etl_offset = '',
                notes = '',
                notes_1 = '',
                verified_mouse_tracker_for_metadata_intake = '',
                notes_on_missing_metadata = ''
            )
        else:
            return ImagingQueue(
        )
        """

    def testImagingQueue(self):
        """Test ImagingQueue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
