# coding: utf-8

"""
    aind-smartsheet-service

     ## aind-smartsheet-service  Service to pull data from SmartSheet.  

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class FundingModel(BaseModel):
    """
    Expected model for the Funding Sheet
    """ # noqa: E501
    project_name: Optional[StrictStr] = None
    subproject: Optional[StrictStr] = None
    project_code: Optional[StrictStr] = None
    funding_institution: Optional[StrictStr] = None
    grant_number: Optional[StrictStr] = None
    fundees: Optional[StrictStr] = None
    investigators: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["project_name", "subproject", "project_code", "funding_institution", "grant_number", "fundees", "investigators"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FundingModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if project_name (nullable) is None
        # and model_fields_set contains the field
        if self.project_name is None and "project_name" in self.model_fields_set:
            _dict['project_name'] = None

        # set to None if subproject (nullable) is None
        # and model_fields_set contains the field
        if self.subproject is None and "subproject" in self.model_fields_set:
            _dict['subproject'] = None

        # set to None if project_code (nullable) is None
        # and model_fields_set contains the field
        if self.project_code is None and "project_code" in self.model_fields_set:
            _dict['project_code'] = None

        # set to None if funding_institution (nullable) is None
        # and model_fields_set contains the field
        if self.funding_institution is None and "funding_institution" in self.model_fields_set:
            _dict['funding_institution'] = None

        # set to None if grant_number (nullable) is None
        # and model_fields_set contains the field
        if self.grant_number is None and "grant_number" in self.model_fields_set:
            _dict['grant_number'] = None

        # set to None if fundees (nullable) is None
        # and model_fields_set contains the field
        if self.fundees is None and "fundees" in self.model_fields_set:
            _dict['fundees'] = None

        # set to None if investigators (nullable) is None
        # and model_fields_set contains the field
        if self.investigators is None and "investigators" in self.model_fields_set:
            _dict['investigators'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FundingModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "project_name": obj.get("project_name"),
            "subproject": obj.get("subproject"),
            "project_code": obj.get("project_code"),
            "funding_institution": obj.get("funding_institution"),
            "grant_number": obj.get("grant_number"),
            "fundees": obj.get("fundees"),
            "investigators": obj.get("investigators")
        })
        return _obj


