# coding: utf-8

"""
    aind-smartsheet-service

     ## aind-smartsheet-service  Service to pull data from SmartSheet.  

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class QcSheet(BaseModel):
    """
    QC Sheet Information.
    """ # noqa: E501
    sample: Optional[StrictStr] = None
    imaging_priority: Optional[StrictStr] = None
    date_sent_for_1x_imaging: Optional[StrictStr] = None
    date_of_tissue_processing_completion: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    genotype: Optional[StrictStr] = None
    label: Optional[StrictStr] = None
    project_description: Optional[StrictStr] = None
    perfusion_date: Optional[StrictStr] = None
    las_injection_notes: Optional[StrictStr] = None
    las_perfusion_dissection_notes: Optional[StrictStr] = None
    perfusion_dissection_quality_notes: Optional[StrictStr] = None
    perfusion_pass_fail: Optional[StrictStr] = None
    labeling_density_notes_olympus_mxv10: Optional[StrictStr] = None
    durotomy_tissue_damage_notes: Optional[StrictStr] = None
    immuno_gross_anatomy_notes: Optional[StrictStr] = None
    immuno_pass_fail: Optional[StrictStr] = None
    digestion_notes: Optional[StrictStr] = None
    digestion_pass_fail: Optional[StrictStr] = None
    special_notes: Optional[StrictStr] = None
    brain_size_at_1x_imaging: Optional[StrictStr] = None
    one_x_screening_link: Optional[StrictStr] = None
    investigator: Optional[StrictStr] = None
    project_name: Optional[StrictStr] = None
    surface_labeling: Optional[StrictStr] = None
    vascular_labeling: Optional[StrictStr] = None
    no_artifacts: Optional[StrictStr] = None
    targeted_sparsity: Optional[StrictStr] = None
    no_surface_labeling: Optional[StrictStr] = None
    no_vascular_labeling: Optional[StrictStr] = None
    targeted_sparsity_q: Optional[StrictStr] = None
    one_x_review_pass_fail: Optional[StrictStr] = None
    one_x_screening_notes_platform_lead: Optional[StrictStr] = None
    one_x_screening_notes_sample_processing_r_a: Optional[StrictStr] = None
    one_x_screening_notes_investigator: Optional[StrictStr] = None
    five_x_imaging_date: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["sample", "imaging_priority", "date_sent_for_1x_imaging", "date_of_tissue_processing_completion", "status", "genotype", "label", "project_description", "perfusion_date", "las_injection_notes", "las_perfusion_dissection_notes", "perfusion_dissection_quality_notes", "perfusion_pass_fail", "labeling_density_notes_olympus_mxv10", "durotomy_tissue_damage_notes", "immuno_gross_anatomy_notes", "immuno_pass_fail", "digestion_notes", "digestion_pass_fail", "special_notes", "brain_size_at_1x_imaging", "one_x_screening_link", "investigator", "project_name", "surface_labeling", "vascular_labeling", "no_artifacts", "targeted_sparsity", "no_surface_labeling", "no_vascular_labeling", "targeted_sparsity_q", "one_x_review_pass_fail", "one_x_screening_notes_platform_lead", "one_x_screening_notes_sample_processing_r_a", "one_x_screening_notes_investigator", "five_x_imaging_date"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QcSheet from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if sample (nullable) is None
        # and model_fields_set contains the field
        if self.sample is None and "sample" in self.model_fields_set:
            _dict['sample'] = None

        # set to None if imaging_priority (nullable) is None
        # and model_fields_set contains the field
        if self.imaging_priority is None and "imaging_priority" in self.model_fields_set:
            _dict['imaging_priority'] = None

        # set to None if date_sent_for_1x_imaging (nullable) is None
        # and model_fields_set contains the field
        if self.date_sent_for_1x_imaging is None and "date_sent_for_1x_imaging" in self.model_fields_set:
            _dict['date_sent_for_1x_imaging'] = None

        # set to None if date_of_tissue_processing_completion (nullable) is None
        # and model_fields_set contains the field
        if self.date_of_tissue_processing_completion is None and "date_of_tissue_processing_completion" in self.model_fields_set:
            _dict['date_of_tissue_processing_completion'] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        # set to None if genotype (nullable) is None
        # and model_fields_set contains the field
        if self.genotype is None and "genotype" in self.model_fields_set:
            _dict['genotype'] = None

        # set to None if label (nullable) is None
        # and model_fields_set contains the field
        if self.label is None and "label" in self.model_fields_set:
            _dict['label'] = None

        # set to None if project_description (nullable) is None
        # and model_fields_set contains the field
        if self.project_description is None and "project_description" in self.model_fields_set:
            _dict['project_description'] = None

        # set to None if perfusion_date (nullable) is None
        # and model_fields_set contains the field
        if self.perfusion_date is None and "perfusion_date" in self.model_fields_set:
            _dict['perfusion_date'] = None

        # set to None if las_injection_notes (nullable) is None
        # and model_fields_set contains the field
        if self.las_injection_notes is None and "las_injection_notes" in self.model_fields_set:
            _dict['las_injection_notes'] = None

        # set to None if las_perfusion_dissection_notes (nullable) is None
        # and model_fields_set contains the field
        if self.las_perfusion_dissection_notes is None and "las_perfusion_dissection_notes" in self.model_fields_set:
            _dict['las_perfusion_dissection_notes'] = None

        # set to None if perfusion_dissection_quality_notes (nullable) is None
        # and model_fields_set contains the field
        if self.perfusion_dissection_quality_notes is None and "perfusion_dissection_quality_notes" in self.model_fields_set:
            _dict['perfusion_dissection_quality_notes'] = None

        # set to None if perfusion_pass_fail (nullable) is None
        # and model_fields_set contains the field
        if self.perfusion_pass_fail is None and "perfusion_pass_fail" in self.model_fields_set:
            _dict['perfusion_pass_fail'] = None

        # set to None if labeling_density_notes_olympus_mxv10 (nullable) is None
        # and model_fields_set contains the field
        if self.labeling_density_notes_olympus_mxv10 is None and "labeling_density_notes_olympus_mxv10" in self.model_fields_set:
            _dict['labeling_density_notes_olympus_mxv10'] = None

        # set to None if durotomy_tissue_damage_notes (nullable) is None
        # and model_fields_set contains the field
        if self.durotomy_tissue_damage_notes is None and "durotomy_tissue_damage_notes" in self.model_fields_set:
            _dict['durotomy_tissue_damage_notes'] = None

        # set to None if immuno_gross_anatomy_notes (nullable) is None
        # and model_fields_set contains the field
        if self.immuno_gross_anatomy_notes is None and "immuno_gross_anatomy_notes" in self.model_fields_set:
            _dict['immuno_gross_anatomy_notes'] = None

        # set to None if immuno_pass_fail (nullable) is None
        # and model_fields_set contains the field
        if self.immuno_pass_fail is None and "immuno_pass_fail" in self.model_fields_set:
            _dict['immuno_pass_fail'] = None

        # set to None if digestion_notes (nullable) is None
        # and model_fields_set contains the field
        if self.digestion_notes is None and "digestion_notes" in self.model_fields_set:
            _dict['digestion_notes'] = None

        # set to None if digestion_pass_fail (nullable) is None
        # and model_fields_set contains the field
        if self.digestion_pass_fail is None and "digestion_pass_fail" in self.model_fields_set:
            _dict['digestion_pass_fail'] = None

        # set to None if special_notes (nullable) is None
        # and model_fields_set contains the field
        if self.special_notes is None and "special_notes" in self.model_fields_set:
            _dict['special_notes'] = None

        # set to None if brain_size_at_1x_imaging (nullable) is None
        # and model_fields_set contains the field
        if self.brain_size_at_1x_imaging is None and "brain_size_at_1x_imaging" in self.model_fields_set:
            _dict['brain_size_at_1x_imaging'] = None

        # set to None if one_x_screening_link (nullable) is None
        # and model_fields_set contains the field
        if self.one_x_screening_link is None and "one_x_screening_link" in self.model_fields_set:
            _dict['one_x_screening_link'] = None

        # set to None if investigator (nullable) is None
        # and model_fields_set contains the field
        if self.investigator is None and "investigator" in self.model_fields_set:
            _dict['investigator'] = None

        # set to None if project_name (nullable) is None
        # and model_fields_set contains the field
        if self.project_name is None and "project_name" in self.model_fields_set:
            _dict['project_name'] = None

        # set to None if surface_labeling (nullable) is None
        # and model_fields_set contains the field
        if self.surface_labeling is None and "surface_labeling" in self.model_fields_set:
            _dict['surface_labeling'] = None

        # set to None if vascular_labeling (nullable) is None
        # and model_fields_set contains the field
        if self.vascular_labeling is None and "vascular_labeling" in self.model_fields_set:
            _dict['vascular_labeling'] = None

        # set to None if no_artifacts (nullable) is None
        # and model_fields_set contains the field
        if self.no_artifacts is None and "no_artifacts" in self.model_fields_set:
            _dict['no_artifacts'] = None

        # set to None if targeted_sparsity (nullable) is None
        # and model_fields_set contains the field
        if self.targeted_sparsity is None and "targeted_sparsity" in self.model_fields_set:
            _dict['targeted_sparsity'] = None

        # set to None if no_surface_labeling (nullable) is None
        # and model_fields_set contains the field
        if self.no_surface_labeling is None and "no_surface_labeling" in self.model_fields_set:
            _dict['no_surface_labeling'] = None

        # set to None if no_vascular_labeling (nullable) is None
        # and model_fields_set contains the field
        if self.no_vascular_labeling is None and "no_vascular_labeling" in self.model_fields_set:
            _dict['no_vascular_labeling'] = None

        # set to None if targeted_sparsity_q (nullable) is None
        # and model_fields_set contains the field
        if self.targeted_sparsity_q is None and "targeted_sparsity_q" in self.model_fields_set:
            _dict['targeted_sparsity_q'] = None

        # set to None if one_x_review_pass_fail (nullable) is None
        # and model_fields_set contains the field
        if self.one_x_review_pass_fail is None and "one_x_review_pass_fail" in self.model_fields_set:
            _dict['one_x_review_pass_fail'] = None

        # set to None if one_x_screening_notes_platform_lead (nullable) is None
        # and model_fields_set contains the field
        if self.one_x_screening_notes_platform_lead is None and "one_x_screening_notes_platform_lead" in self.model_fields_set:
            _dict['one_x_screening_notes_platform_lead'] = None

        # set to None if one_x_screening_notes_sample_processing_r_a (nullable) is None
        # and model_fields_set contains the field
        if self.one_x_screening_notes_sample_processing_r_a is None and "one_x_screening_notes_sample_processing_r_a" in self.model_fields_set:
            _dict['one_x_screening_notes_sample_processing_r_a'] = None

        # set to None if one_x_screening_notes_investigator (nullable) is None
        # and model_fields_set contains the field
        if self.one_x_screening_notes_investigator is None and "one_x_screening_notes_investigator" in self.model_fields_set:
            _dict['one_x_screening_notes_investigator'] = None

        # set to None if five_x_imaging_date (nullable) is None
        # and model_fields_set contains the field
        if self.five_x_imaging_date is None and "five_x_imaging_date" in self.model_fields_set:
            _dict['five_x_imaging_date'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QcSheet from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sample": obj.get("sample"),
            "imaging_priority": obj.get("imaging_priority"),
            "date_sent_for_1x_imaging": obj.get("date_sent_for_1x_imaging"),
            "date_of_tissue_processing_completion": obj.get("date_of_tissue_processing_completion"),
            "status": obj.get("status"),
            "genotype": obj.get("genotype"),
            "label": obj.get("label"),
            "project_description": obj.get("project_description"),
            "perfusion_date": obj.get("perfusion_date"),
            "las_injection_notes": obj.get("las_injection_notes"),
            "las_perfusion_dissection_notes": obj.get("las_perfusion_dissection_notes"),
            "perfusion_dissection_quality_notes": obj.get("perfusion_dissection_quality_notes"),
            "perfusion_pass_fail": obj.get("perfusion_pass_fail"),
            "labeling_density_notes_olympus_mxv10": obj.get("labeling_density_notes_olympus_mxv10"),
            "durotomy_tissue_damage_notes": obj.get("durotomy_tissue_damage_notes"),
            "immuno_gross_anatomy_notes": obj.get("immuno_gross_anatomy_notes"),
            "immuno_pass_fail": obj.get("immuno_pass_fail"),
            "digestion_notes": obj.get("digestion_notes"),
            "digestion_pass_fail": obj.get("digestion_pass_fail"),
            "special_notes": obj.get("special_notes"),
            "brain_size_at_1x_imaging": obj.get("brain_size_at_1x_imaging"),
            "one_x_screening_link": obj.get("one_x_screening_link"),
            "investigator": obj.get("investigator"),
            "project_name": obj.get("project_name"),
            "surface_labeling": obj.get("surface_labeling"),
            "vascular_labeling": obj.get("vascular_labeling"),
            "no_artifacts": obj.get("no_artifacts"),
            "targeted_sparsity": obj.get("targeted_sparsity"),
            "no_surface_labeling": obj.get("no_surface_labeling"),
            "no_vascular_labeling": obj.get("no_vascular_labeling"),
            "targeted_sparsity_q": obj.get("targeted_sparsity_q"),
            "one_x_review_pass_fail": obj.get("one_x_review_pass_fail"),
            "one_x_screening_notes_platform_lead": obj.get("one_x_screening_notes_platform_lead"),
            "one_x_screening_notes_sample_processing_r_a": obj.get("one_x_screening_notes_sample_processing_r_a"),
            "one_x_screening_notes_investigator": obj.get("one_x_screening_notes_investigator"),
            "five_x_imaging_date": obj.get("five_x_imaging_date")
        })
        return _obj


