# coding: utf-8

"""
    aind-smartsheet-service

     ## aind-smartsheet-service  Service to pull data from SmartSheet.  

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SampleTracking(BaseModel):
    """
    Sample Tracking Sheet Information.
    """ # noqa: E501
    external_sample: Optional[StrictStr] = None
    screening_status: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    sample: Optional[StrictStr] = None
    genotype: Optional[StrictStr] = None
    processing_lead: Optional[StrictStr] = None
    project: Optional[StrictStr] = None
    project_description: Optional[StrictStr] = None
    project_name: Optional[StrictStr] = None
    label: Optional[StrictStr] = None
    age_of_injection: Optional[StrictStr] = None
    virus_dose: Optional[StrictStr] = None
    dcm_delipidation_start: Optional[StrictStr] = None
    dcm_delipidation_end: Optional[StrictStr] = None
    sbip_delipidation_start: Optional[StrictStr] = None
    sbip_delipidation_end: Optional[StrictStr] = None
    immuno_primary_ab_start_date: Optional[StrictStr] = None
    immuno_primary_antibody1: Optional[StrictStr] = None
    mass_of_primary_antibody1_used_per_brain_ug: Optional[StrictStr] = None
    primary_antibody1_catalog_num: Optional[StrictStr] = None
    primary_antibody1_lot_num: Optional[StrictStr] = None
    immuno_primary_antibody2: Optional[StrictStr] = None
    mass_of_primary_antibody2_used_per_brain_ug: Optional[StrictStr] = None
    primary_antibody2_catalog_num: Optional[StrictStr] = None
    primary_antibody2_lot_num: Optional[StrictStr] = None
    immuno_primary_antibody3: Optional[StrictStr] = None
    mass_of_primary_antibody3_used_per_brain_ug: Optional[StrictStr] = None
    primary_antibody3_catalog_num: Optional[StrictStr] = None
    primary_antibody3_lot_num: Optional[StrictStr] = None
    primary_antibody_rrid: Optional[StrictStr] = None
    immuno_secondary_ab_start_date: Optional[StrictStr] = None
    immuno_secondary_antibody1: Optional[StrictStr] = None
    mass_of_secondary_antibody1_used_per_brain_ug: Optional[StrictStr] = None
    secondary_antibody1_catalog_num: Optional[StrictStr] = None
    secondary_antibody1_lot_num: Optional[StrictStr] = None
    immuno_secondary_antibody2: Optional[StrictStr] = None
    mass_of_secondary_antibody2_used_per_brain_ug: Optional[StrictStr] = None
    secondary_antibody2_catalog_num: Optional[StrictStr] = None
    secondary_antibody2_lot_num: Optional[StrictStr] = None
    immuno_secondary_antibody3: Optional[StrictStr] = None
    mass_of_secondary_antibody3_used_per_brain_ug: Optional[StrictStr] = None
    secondary_antibody3_catalog_num: Optional[StrictStr] = None
    secondary_antibody3_lot_num: Optional[StrictStr] = None
    secondary_antibody_rrid: Optional[StrictStr] = None
    fluorophore1: Optional[StrictStr] = None
    fluorophore2: Optional[StrictStr] = None
    fluorophore3: Optional[StrictStr] = None
    fluorophore_t: Optional[StrictStr] = None
    gelation_mbs_start: Optional[StrictStr] = None
    gelation_mbs_end: Optional[StrictStr] = None
    gelation_ac_x_start: Optional[StrictStr] = None
    gelation_ac_x_end: Optional[StrictStr] = None
    gelation_pbs_wash_start: Optional[StrictStr] = None
    gelation_pbs_wash_end: Optional[StrictStr] = None
    gelation_stock_xva_044_equilibration_start: Optional[StrictStr] = None
    gelation_stock_xva_044_equilibration_end: Optional[StrictStr] = None
    gelation_prok_rt_start: Optional[StrictStr] = None
    gelation_prok_rt_end: Optional[StrictStr] = None
    duration_days: Optional[StrictStr] = None
    gelation_add_l_prok_37c_start: Optional[StrictStr] = None
    gelation_add_l_prok_37c_end: Optional[StrictStr] = None
    duration_days_gelation_add_l_prok_37c: Optional[StrictStr] = None
    pbs_wash_start: Optional[StrictStr] = None
    pbs_wash_end: Optional[StrictStr] = None
    date_of_storage_in_pbs_az_0_05_4c: Optional[StrictStr] = None
    notes: Optional[StrictStr] = None
    notes_ii: Optional[StrictStr] = None
    notes_iii: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["external_sample", "screening_status", "status", "sample", "genotype", "processing_lead", "project", "project_description", "project_name", "label", "age_of_injection", "virus_dose", "dcm_delipidation_start", "dcm_delipidation_end", "sbip_delipidation_start", "sbip_delipidation_end", "immuno_primary_ab_start_date", "immuno_primary_antibody1", "mass_of_primary_antibody1_used_per_brain_ug", "primary_antibody1_catalog_num", "primary_antibody1_lot_num", "immuno_primary_antibody2", "mass_of_primary_antibody2_used_per_brain_ug", "primary_antibody2_catalog_num", "primary_antibody2_lot_num", "immuno_primary_antibody3", "mass_of_primary_antibody3_used_per_brain_ug", "primary_antibody3_catalog_num", "primary_antibody3_lot_num", "primary_antibody_rrid", "immuno_secondary_ab_start_date", "immuno_secondary_antibody1", "mass_of_secondary_antibody1_used_per_brain_ug", "secondary_antibody1_catalog_num", "secondary_antibody1_lot_num", "immuno_secondary_antibody2", "mass_of_secondary_antibody2_used_per_brain_ug", "secondary_antibody2_catalog_num", "secondary_antibody2_lot_num", "immuno_secondary_antibody3", "mass_of_secondary_antibody3_used_per_brain_ug", "secondary_antibody3_catalog_num", "secondary_antibody3_lot_num", "secondary_antibody_rrid", "fluorophore1", "fluorophore2", "fluorophore3", "fluorophore_t", "gelation_mbs_start", "gelation_mbs_end", "gelation_ac_x_start", "gelation_ac_x_end", "gelation_pbs_wash_start", "gelation_pbs_wash_end", "gelation_stock_xva_044_equilibration_start", "gelation_stock_xva_044_equilibration_end", "gelation_prok_rt_start", "gelation_prok_rt_end", "duration_days", "gelation_add_l_prok_37c_start", "gelation_add_l_prok_37c_end", "duration_days_gelation_add_l_prok_37c", "pbs_wash_start", "pbs_wash_end", "date_of_storage_in_pbs_az_0_05_4c", "notes", "notes_ii", "notes_iii"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SampleTracking from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if external_sample (nullable) is None
        # and model_fields_set contains the field
        if self.external_sample is None and "external_sample" in self.model_fields_set:
            _dict['external_sample'] = None

        # set to None if screening_status (nullable) is None
        # and model_fields_set contains the field
        if self.screening_status is None and "screening_status" in self.model_fields_set:
            _dict['screening_status'] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        # set to None if sample (nullable) is None
        # and model_fields_set contains the field
        if self.sample is None and "sample" in self.model_fields_set:
            _dict['sample'] = None

        # set to None if genotype (nullable) is None
        # and model_fields_set contains the field
        if self.genotype is None and "genotype" in self.model_fields_set:
            _dict['genotype'] = None

        # set to None if processing_lead (nullable) is None
        # and model_fields_set contains the field
        if self.processing_lead is None and "processing_lead" in self.model_fields_set:
            _dict['processing_lead'] = None

        # set to None if project (nullable) is None
        # and model_fields_set contains the field
        if self.project is None and "project" in self.model_fields_set:
            _dict['project'] = None

        # set to None if project_description (nullable) is None
        # and model_fields_set contains the field
        if self.project_description is None and "project_description" in self.model_fields_set:
            _dict['project_description'] = None

        # set to None if project_name (nullable) is None
        # and model_fields_set contains the field
        if self.project_name is None and "project_name" in self.model_fields_set:
            _dict['project_name'] = None

        # set to None if label (nullable) is None
        # and model_fields_set contains the field
        if self.label is None and "label" in self.model_fields_set:
            _dict['label'] = None

        # set to None if age_of_injection (nullable) is None
        # and model_fields_set contains the field
        if self.age_of_injection is None and "age_of_injection" in self.model_fields_set:
            _dict['age_of_injection'] = None

        # set to None if virus_dose (nullable) is None
        # and model_fields_set contains the field
        if self.virus_dose is None and "virus_dose" in self.model_fields_set:
            _dict['virus_dose'] = None

        # set to None if dcm_delipidation_start (nullable) is None
        # and model_fields_set contains the field
        if self.dcm_delipidation_start is None and "dcm_delipidation_start" in self.model_fields_set:
            _dict['dcm_delipidation_start'] = None

        # set to None if dcm_delipidation_end (nullable) is None
        # and model_fields_set contains the field
        if self.dcm_delipidation_end is None and "dcm_delipidation_end" in self.model_fields_set:
            _dict['dcm_delipidation_end'] = None

        # set to None if sbip_delipidation_start (nullable) is None
        # and model_fields_set contains the field
        if self.sbip_delipidation_start is None and "sbip_delipidation_start" in self.model_fields_set:
            _dict['sbip_delipidation_start'] = None

        # set to None if sbip_delipidation_end (nullable) is None
        # and model_fields_set contains the field
        if self.sbip_delipidation_end is None and "sbip_delipidation_end" in self.model_fields_set:
            _dict['sbip_delipidation_end'] = None

        # set to None if immuno_primary_ab_start_date (nullable) is None
        # and model_fields_set contains the field
        if self.immuno_primary_ab_start_date is None and "immuno_primary_ab_start_date" in self.model_fields_set:
            _dict['immuno_primary_ab_start_date'] = None

        # set to None if immuno_primary_antibody1 (nullable) is None
        # and model_fields_set contains the field
        if self.immuno_primary_antibody1 is None and "immuno_primary_antibody1" in self.model_fields_set:
            _dict['immuno_primary_antibody1'] = None

        # set to None if mass_of_primary_antibody1_used_per_brain_ug (nullable) is None
        # and model_fields_set contains the field
        if self.mass_of_primary_antibody1_used_per_brain_ug is None and "mass_of_primary_antibody1_used_per_brain_ug" in self.model_fields_set:
            _dict['mass_of_primary_antibody1_used_per_brain_ug'] = None

        # set to None if primary_antibody1_catalog_num (nullable) is None
        # and model_fields_set contains the field
        if self.primary_antibody1_catalog_num is None and "primary_antibody1_catalog_num" in self.model_fields_set:
            _dict['primary_antibody1_catalog_num'] = None

        # set to None if primary_antibody1_lot_num (nullable) is None
        # and model_fields_set contains the field
        if self.primary_antibody1_lot_num is None and "primary_antibody1_lot_num" in self.model_fields_set:
            _dict['primary_antibody1_lot_num'] = None

        # set to None if immuno_primary_antibody2 (nullable) is None
        # and model_fields_set contains the field
        if self.immuno_primary_antibody2 is None and "immuno_primary_antibody2" in self.model_fields_set:
            _dict['immuno_primary_antibody2'] = None

        # set to None if mass_of_primary_antibody2_used_per_brain_ug (nullable) is None
        # and model_fields_set contains the field
        if self.mass_of_primary_antibody2_used_per_brain_ug is None and "mass_of_primary_antibody2_used_per_brain_ug" in self.model_fields_set:
            _dict['mass_of_primary_antibody2_used_per_brain_ug'] = None

        # set to None if primary_antibody2_catalog_num (nullable) is None
        # and model_fields_set contains the field
        if self.primary_antibody2_catalog_num is None and "primary_antibody2_catalog_num" in self.model_fields_set:
            _dict['primary_antibody2_catalog_num'] = None

        # set to None if primary_antibody2_lot_num (nullable) is None
        # and model_fields_set contains the field
        if self.primary_antibody2_lot_num is None and "primary_antibody2_lot_num" in self.model_fields_set:
            _dict['primary_antibody2_lot_num'] = None

        # set to None if immuno_primary_antibody3 (nullable) is None
        # and model_fields_set contains the field
        if self.immuno_primary_antibody3 is None and "immuno_primary_antibody3" in self.model_fields_set:
            _dict['immuno_primary_antibody3'] = None

        # set to None if mass_of_primary_antibody3_used_per_brain_ug (nullable) is None
        # and model_fields_set contains the field
        if self.mass_of_primary_antibody3_used_per_brain_ug is None and "mass_of_primary_antibody3_used_per_brain_ug" in self.model_fields_set:
            _dict['mass_of_primary_antibody3_used_per_brain_ug'] = None

        # set to None if primary_antibody3_catalog_num (nullable) is None
        # and model_fields_set contains the field
        if self.primary_antibody3_catalog_num is None and "primary_antibody3_catalog_num" in self.model_fields_set:
            _dict['primary_antibody3_catalog_num'] = None

        # set to None if primary_antibody3_lot_num (nullable) is None
        # and model_fields_set contains the field
        if self.primary_antibody3_lot_num is None and "primary_antibody3_lot_num" in self.model_fields_set:
            _dict['primary_antibody3_lot_num'] = None

        # set to None if primary_antibody_rrid (nullable) is None
        # and model_fields_set contains the field
        if self.primary_antibody_rrid is None and "primary_antibody_rrid" in self.model_fields_set:
            _dict['primary_antibody_rrid'] = None

        # set to None if immuno_secondary_ab_start_date (nullable) is None
        # and model_fields_set contains the field
        if self.immuno_secondary_ab_start_date is None and "immuno_secondary_ab_start_date" in self.model_fields_set:
            _dict['immuno_secondary_ab_start_date'] = None

        # set to None if immuno_secondary_antibody1 (nullable) is None
        # and model_fields_set contains the field
        if self.immuno_secondary_antibody1 is None and "immuno_secondary_antibody1" in self.model_fields_set:
            _dict['immuno_secondary_antibody1'] = None

        # set to None if mass_of_secondary_antibody1_used_per_brain_ug (nullable) is None
        # and model_fields_set contains the field
        if self.mass_of_secondary_antibody1_used_per_brain_ug is None and "mass_of_secondary_antibody1_used_per_brain_ug" in self.model_fields_set:
            _dict['mass_of_secondary_antibody1_used_per_brain_ug'] = None

        # set to None if secondary_antibody1_catalog_num (nullable) is None
        # and model_fields_set contains the field
        if self.secondary_antibody1_catalog_num is None and "secondary_antibody1_catalog_num" in self.model_fields_set:
            _dict['secondary_antibody1_catalog_num'] = None

        # set to None if secondary_antibody1_lot_num (nullable) is None
        # and model_fields_set contains the field
        if self.secondary_antibody1_lot_num is None and "secondary_antibody1_lot_num" in self.model_fields_set:
            _dict['secondary_antibody1_lot_num'] = None

        # set to None if immuno_secondary_antibody2 (nullable) is None
        # and model_fields_set contains the field
        if self.immuno_secondary_antibody2 is None and "immuno_secondary_antibody2" in self.model_fields_set:
            _dict['immuno_secondary_antibody2'] = None

        # set to None if mass_of_secondary_antibody2_used_per_brain_ug (nullable) is None
        # and model_fields_set contains the field
        if self.mass_of_secondary_antibody2_used_per_brain_ug is None and "mass_of_secondary_antibody2_used_per_brain_ug" in self.model_fields_set:
            _dict['mass_of_secondary_antibody2_used_per_brain_ug'] = None

        # set to None if secondary_antibody2_catalog_num (nullable) is None
        # and model_fields_set contains the field
        if self.secondary_antibody2_catalog_num is None and "secondary_antibody2_catalog_num" in self.model_fields_set:
            _dict['secondary_antibody2_catalog_num'] = None

        # set to None if secondary_antibody2_lot_num (nullable) is None
        # and model_fields_set contains the field
        if self.secondary_antibody2_lot_num is None and "secondary_antibody2_lot_num" in self.model_fields_set:
            _dict['secondary_antibody2_lot_num'] = None

        # set to None if immuno_secondary_antibody3 (nullable) is None
        # and model_fields_set contains the field
        if self.immuno_secondary_antibody3 is None and "immuno_secondary_antibody3" in self.model_fields_set:
            _dict['immuno_secondary_antibody3'] = None

        # set to None if mass_of_secondary_antibody3_used_per_brain_ug (nullable) is None
        # and model_fields_set contains the field
        if self.mass_of_secondary_antibody3_used_per_brain_ug is None and "mass_of_secondary_antibody3_used_per_brain_ug" in self.model_fields_set:
            _dict['mass_of_secondary_antibody3_used_per_brain_ug'] = None

        # set to None if secondary_antibody3_catalog_num (nullable) is None
        # and model_fields_set contains the field
        if self.secondary_antibody3_catalog_num is None and "secondary_antibody3_catalog_num" in self.model_fields_set:
            _dict['secondary_antibody3_catalog_num'] = None

        # set to None if secondary_antibody3_lot_num (nullable) is None
        # and model_fields_set contains the field
        if self.secondary_antibody3_lot_num is None and "secondary_antibody3_lot_num" in self.model_fields_set:
            _dict['secondary_antibody3_lot_num'] = None

        # set to None if secondary_antibody_rrid (nullable) is None
        # and model_fields_set contains the field
        if self.secondary_antibody_rrid is None and "secondary_antibody_rrid" in self.model_fields_set:
            _dict['secondary_antibody_rrid'] = None

        # set to None if fluorophore1 (nullable) is None
        # and model_fields_set contains the field
        if self.fluorophore1 is None and "fluorophore1" in self.model_fields_set:
            _dict['fluorophore1'] = None

        # set to None if fluorophore2 (nullable) is None
        # and model_fields_set contains the field
        if self.fluorophore2 is None and "fluorophore2" in self.model_fields_set:
            _dict['fluorophore2'] = None

        # set to None if fluorophore3 (nullable) is None
        # and model_fields_set contains the field
        if self.fluorophore3 is None and "fluorophore3" in self.model_fields_set:
            _dict['fluorophore3'] = None

        # set to None if fluorophore_t (nullable) is None
        # and model_fields_set contains the field
        if self.fluorophore_t is None and "fluorophore_t" in self.model_fields_set:
            _dict['fluorophore_t'] = None

        # set to None if gelation_mbs_start (nullable) is None
        # and model_fields_set contains the field
        if self.gelation_mbs_start is None and "gelation_mbs_start" in self.model_fields_set:
            _dict['gelation_mbs_start'] = None

        # set to None if gelation_mbs_end (nullable) is None
        # and model_fields_set contains the field
        if self.gelation_mbs_end is None and "gelation_mbs_end" in self.model_fields_set:
            _dict['gelation_mbs_end'] = None

        # set to None if gelation_ac_x_start (nullable) is None
        # and model_fields_set contains the field
        if self.gelation_ac_x_start is None and "gelation_ac_x_start" in self.model_fields_set:
            _dict['gelation_ac_x_start'] = None

        # set to None if gelation_ac_x_end (nullable) is None
        # and model_fields_set contains the field
        if self.gelation_ac_x_end is None and "gelation_ac_x_end" in self.model_fields_set:
            _dict['gelation_ac_x_end'] = None

        # set to None if gelation_pbs_wash_start (nullable) is None
        # and model_fields_set contains the field
        if self.gelation_pbs_wash_start is None and "gelation_pbs_wash_start" in self.model_fields_set:
            _dict['gelation_pbs_wash_start'] = None

        # set to None if gelation_pbs_wash_end (nullable) is None
        # and model_fields_set contains the field
        if self.gelation_pbs_wash_end is None and "gelation_pbs_wash_end" in self.model_fields_set:
            _dict['gelation_pbs_wash_end'] = None

        # set to None if gelation_stock_xva_044_equilibration_start (nullable) is None
        # and model_fields_set contains the field
        if self.gelation_stock_xva_044_equilibration_start is None and "gelation_stock_xva_044_equilibration_start" in self.model_fields_set:
            _dict['gelation_stock_xva_044_equilibration_start'] = None

        # set to None if gelation_stock_xva_044_equilibration_end (nullable) is None
        # and model_fields_set contains the field
        if self.gelation_stock_xva_044_equilibration_end is None and "gelation_stock_xva_044_equilibration_end" in self.model_fields_set:
            _dict['gelation_stock_xva_044_equilibration_end'] = None

        # set to None if gelation_prok_rt_start (nullable) is None
        # and model_fields_set contains the field
        if self.gelation_prok_rt_start is None and "gelation_prok_rt_start" in self.model_fields_set:
            _dict['gelation_prok_rt_start'] = None

        # set to None if gelation_prok_rt_end (nullable) is None
        # and model_fields_set contains the field
        if self.gelation_prok_rt_end is None and "gelation_prok_rt_end" in self.model_fields_set:
            _dict['gelation_prok_rt_end'] = None

        # set to None if duration_days (nullable) is None
        # and model_fields_set contains the field
        if self.duration_days is None and "duration_days" in self.model_fields_set:
            _dict['duration_days'] = None

        # set to None if gelation_add_l_prok_37c_start (nullable) is None
        # and model_fields_set contains the field
        if self.gelation_add_l_prok_37c_start is None and "gelation_add_l_prok_37c_start" in self.model_fields_set:
            _dict['gelation_add_l_prok_37c_start'] = None

        # set to None if gelation_add_l_prok_37c_end (nullable) is None
        # and model_fields_set contains the field
        if self.gelation_add_l_prok_37c_end is None and "gelation_add_l_prok_37c_end" in self.model_fields_set:
            _dict['gelation_add_l_prok_37c_end'] = None

        # set to None if duration_days_gelation_add_l_prok_37c (nullable) is None
        # and model_fields_set contains the field
        if self.duration_days_gelation_add_l_prok_37c is None and "duration_days_gelation_add_l_prok_37c" in self.model_fields_set:
            _dict['duration_days_gelation_add_l_prok_37c'] = None

        # set to None if pbs_wash_start (nullable) is None
        # and model_fields_set contains the field
        if self.pbs_wash_start is None and "pbs_wash_start" in self.model_fields_set:
            _dict['pbs_wash_start'] = None

        # set to None if pbs_wash_end (nullable) is None
        # and model_fields_set contains the field
        if self.pbs_wash_end is None and "pbs_wash_end" in self.model_fields_set:
            _dict['pbs_wash_end'] = None

        # set to None if date_of_storage_in_pbs_az_0_05_4c (nullable) is None
        # and model_fields_set contains the field
        if self.date_of_storage_in_pbs_az_0_05_4c is None and "date_of_storage_in_pbs_az_0_05_4c" in self.model_fields_set:
            _dict['date_of_storage_in_pbs_az_0_05_4c'] = None

        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict['notes'] = None

        # set to None if notes_ii (nullable) is None
        # and model_fields_set contains the field
        if self.notes_ii is None and "notes_ii" in self.model_fields_set:
            _dict['notes_ii'] = None

        # set to None if notes_iii (nullable) is None
        # and model_fields_set contains the field
        if self.notes_iii is None and "notes_iii" in self.model_fields_set:
            _dict['notes_iii'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SampleTracking from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "external_sample": obj.get("external_sample"),
            "screening_status": obj.get("screening_status"),
            "status": obj.get("status"),
            "sample": obj.get("sample"),
            "genotype": obj.get("genotype"),
            "processing_lead": obj.get("processing_lead"),
            "project": obj.get("project"),
            "project_description": obj.get("project_description"),
            "project_name": obj.get("project_name"),
            "label": obj.get("label"),
            "age_of_injection": obj.get("age_of_injection"),
            "virus_dose": obj.get("virus_dose"),
            "dcm_delipidation_start": obj.get("dcm_delipidation_start"),
            "dcm_delipidation_end": obj.get("dcm_delipidation_end"),
            "sbip_delipidation_start": obj.get("sbip_delipidation_start"),
            "sbip_delipidation_end": obj.get("sbip_delipidation_end"),
            "immuno_primary_ab_start_date": obj.get("immuno_primary_ab_start_date"),
            "immuno_primary_antibody1": obj.get("immuno_primary_antibody1"),
            "mass_of_primary_antibody1_used_per_brain_ug": obj.get("mass_of_primary_antibody1_used_per_brain_ug"),
            "primary_antibody1_catalog_num": obj.get("primary_antibody1_catalog_num"),
            "primary_antibody1_lot_num": obj.get("primary_antibody1_lot_num"),
            "immuno_primary_antibody2": obj.get("immuno_primary_antibody2"),
            "mass_of_primary_antibody2_used_per_brain_ug": obj.get("mass_of_primary_antibody2_used_per_brain_ug"),
            "primary_antibody2_catalog_num": obj.get("primary_antibody2_catalog_num"),
            "primary_antibody2_lot_num": obj.get("primary_antibody2_lot_num"),
            "immuno_primary_antibody3": obj.get("immuno_primary_antibody3"),
            "mass_of_primary_antibody3_used_per_brain_ug": obj.get("mass_of_primary_antibody3_used_per_brain_ug"),
            "primary_antibody3_catalog_num": obj.get("primary_antibody3_catalog_num"),
            "primary_antibody3_lot_num": obj.get("primary_antibody3_lot_num"),
            "primary_antibody_rrid": obj.get("primary_antibody_rrid"),
            "immuno_secondary_ab_start_date": obj.get("immuno_secondary_ab_start_date"),
            "immuno_secondary_antibody1": obj.get("immuno_secondary_antibody1"),
            "mass_of_secondary_antibody1_used_per_brain_ug": obj.get("mass_of_secondary_antibody1_used_per_brain_ug"),
            "secondary_antibody1_catalog_num": obj.get("secondary_antibody1_catalog_num"),
            "secondary_antibody1_lot_num": obj.get("secondary_antibody1_lot_num"),
            "immuno_secondary_antibody2": obj.get("immuno_secondary_antibody2"),
            "mass_of_secondary_antibody2_used_per_brain_ug": obj.get("mass_of_secondary_antibody2_used_per_brain_ug"),
            "secondary_antibody2_catalog_num": obj.get("secondary_antibody2_catalog_num"),
            "secondary_antibody2_lot_num": obj.get("secondary_antibody2_lot_num"),
            "immuno_secondary_antibody3": obj.get("immuno_secondary_antibody3"),
            "mass_of_secondary_antibody3_used_per_brain_ug": obj.get("mass_of_secondary_antibody3_used_per_brain_ug"),
            "secondary_antibody3_catalog_num": obj.get("secondary_antibody3_catalog_num"),
            "secondary_antibody3_lot_num": obj.get("secondary_antibody3_lot_num"),
            "secondary_antibody_rrid": obj.get("secondary_antibody_rrid"),
            "fluorophore1": obj.get("fluorophore1"),
            "fluorophore2": obj.get("fluorophore2"),
            "fluorophore3": obj.get("fluorophore3"),
            "fluorophore_t": obj.get("fluorophore_t"),
            "gelation_mbs_start": obj.get("gelation_mbs_start"),
            "gelation_mbs_end": obj.get("gelation_mbs_end"),
            "gelation_ac_x_start": obj.get("gelation_ac_x_start"),
            "gelation_ac_x_end": obj.get("gelation_ac_x_end"),
            "gelation_pbs_wash_start": obj.get("gelation_pbs_wash_start"),
            "gelation_pbs_wash_end": obj.get("gelation_pbs_wash_end"),
            "gelation_stock_xva_044_equilibration_start": obj.get("gelation_stock_xva_044_equilibration_start"),
            "gelation_stock_xva_044_equilibration_end": obj.get("gelation_stock_xva_044_equilibration_end"),
            "gelation_prok_rt_start": obj.get("gelation_prok_rt_start"),
            "gelation_prok_rt_end": obj.get("gelation_prok_rt_end"),
            "duration_days": obj.get("duration_days"),
            "gelation_add_l_prok_37c_start": obj.get("gelation_add_l_prok_37c_start"),
            "gelation_add_l_prok_37c_end": obj.get("gelation_add_l_prok_37c_end"),
            "duration_days_gelation_add_l_prok_37c": obj.get("duration_days_gelation_add_l_prok_37c"),
            "pbs_wash_start": obj.get("pbs_wash_start"),
            "pbs_wash_end": obj.get("pbs_wash_end"),
            "date_of_storage_in_pbs_az_0_05_4c": obj.get("date_of_storage_in_pbs_az_0_05_4c"),
            "notes": obj.get("notes"),
            "notes_ii": obj.get("notes_ii"),
            "notes_iii": obj.get("notes_iii")
        })
        return _obj


